tb-17 Cria componente de checkbox
studiovisual/base-theme pull request #17
Opened 2023-12-07 05:05 UTC by jeffersonrucustudiovisual

# Checkbox

Componente de formulário checkbox.

## Utilização

   ```blade
   <x-checkbox></x-checkbox>
   ```

## Parâmetros

### icon

- **check -** Exibir o componente checkbox com um ícone de check no centro quando estiver ativado.

- **line -** Exibe o componente checkbox com um ícone de linha branca na horizontal ao centro  quando estiver ativado.

## Exemplo

   ```blade
   <x-checkbox icon="check"> Texto </x-checkbox>
   ```

   OU

   ```blade
   <x-checkbox icon="check" />
   ```

<p align="right">(<a href="../README.md">voltar</a>)</p>

2023-12-07 13:01 UTC, aresnoname requested changes
Verificar pontos:
* Está faltando icone padrão
* Corrigir verificação de $slot

2023-12-07 16:59 UTC, tiagopapile commented on app/View/Components/Checkbox.php
> +    protected string $view = '';
Essa propriedade parece não estar sendo utilizada.

2023-12-07 17:04 UTC, tiagopapile requested changes
Verificar comentários.

2023-12-07 17:11 UTC, tiagopapile commented on resources/views/components/forms/checkbox.blade.php
> +<div class="flex gap-8">
Adicionar a class 'checkbox'.

2023-12-07 17:11 UTC, tiagopapile commented on resources/views/components/forms/checkbox.blade.php
> +    <label class="hover:cursor-pointer" for="{{ $attributes['id'] ?? '' }}"> {{ $slot }} </label>
Adicionar a class 'checkbox__label'.

2023-12-08 04:07 UTC, jeffersonrucustudiovisual commented on app/View/Components/Checkbox.php
> +        switch ($icon) {
@tiagopapile : modo indeterminate adicionado

----

@aresnoname :  Fui consultar a documentação do sage-directives e, ao ler sobre como o @notempty realiza sua verificação, percebi que ele já contempla o cenário em que a string está vazia ou não existe, visto que o método empty do PHP já faz essa validação.

Posso ter interpretado a documentação errado também haha, mas fiz alguns testes e acredito que para esse cenário atenda sim.

## Testes PHP

![image](https://github.com/studiovisual/base-theme/assets/113918065/c4233d18-10e5-461c-8e69-513c1e8f980f)


## Implementação @notempty

![image](https://github.com/studiovisual/base-theme/assets/113918065/c0e0e38d-fce1-4497-83a9-43b689f9255f)

2023-12-08 04:07 UTC, jeffersonrucustudiovisual commented on resources/views/components/forms/checkbox.blade.php
> +  @notempty($slot)
@aresnoname :  Fui consultar a documentação do sage-directives e, ao ler sobre como o @notempty realiza sua verificação, percebi que ele já contempla o cenário em que a string está vazia ou não existe, visto que o método empty do PHP já faz essa validação.

Posso ter interpretado a documentação errado também haha, mas fiz alguns testes e acredito que para esse cenário atenda sim.

## Testes PHP

![image](https://github.com/studiovisual/base-theme/assets/113918065/c4233d18-10e5-461c-8e69-513c1e8f980f)


## Implementação @notempty

![image](https://github.com/studiovisual/base-theme/assets/113918065/c0e0e38d-fce1-4497-83a9-43b689f9255f)

2023-12-08 04:32 UTC, jeffersonrucustudiovisual commented on resources/views/components/forms/checkbox.blade.php
> +      $attributes->merge([
Ajuste realizado

2023-12-08 04:33 UTC, jeffersonrucustudiovisual commented on resources/views/components/forms/checkbox.blade.php
> +<div class="flex gap-8">
Ajuste realizado

2023-12-08 04:34 UTC, jeffersonrucustudiovisual commented on resources/views/components/forms/checkbox.blade.php
> +    <label class="hover:cursor-pointer" for="{{ $attributes['id'] ?? '' }}"> {{ $slot }} </label>
Como `<label>` virou o elemento pai não foi adicionado `checkbox__label ` e sim `checkbox `

2023-12-08 12:07 UTC, aresnoname requested changes
Revisar pontos:
* Talvez adicionar um checkbox apenas com `disabled`
* Verificação de `$slot`

2023-12-08 12:07 UTC, aresnoname commented on resources/views/components.blade.php
> +          <x-checkbox disabled checked />
Dúvida: acho que seria interessante colocar também um checkbox apenas `disabled` sem `checked` para o QA não ter dúvidas, o que acha ?

Para ambos os casos, com e sem `$slot`

2023-12-08 13:44 UTC, tiagopapile commented on resources/views/components.blade.php
> +    <div>
Colocar um subtítulo pra cada exemplo. Dessa forma fica mais fácil de identificarmos e do QA testar também.

2023-12-08 14:35 UTC, jeffersonrucustudiovisual commented on resources/views/components/forms/checkbox.blade.php
> +          checkbox__input relative appearance-none w-20 h-20
Ajuste Realizado

2023-12-08 15:56 UTC, jeffersonrucustudiovisual commented on resources/views/components.blade.php
> +    <div>
Ajuste realizado [645b31f](https://github.com/studiovisual/base-theme/pull/17/commits/645b31fd1a546894030e96b39774492c6508f371)

2023-12-08 15:56 UTC, jeffersonrucustudiovisual commented on resources/views/components.blade.php
> +    <div>
<img width="1440" alt="image" src="https://github.com/studiovisual/base-theme/assets/113918065/a213e6c6-8927-44d3-a706-6d47918146c6">

2023-12-08 15:57 UTC, jeffersonrucustudiovisual commented on resources/views/components.blade.php
> +          <x-checkbox disabled checked />
<img width="1440" alt="image" src="https://github.com/studiovisual/base-theme/assets/113918065/ab9f5c97-a290-4bc9-8885-1de02b595e66">

2023-12-08 16:58 UTC, aresnoname approved these changes
As solicitações que fiz, esta OK!

2023-12-08 17:44 UTC, merged