tb-16 Cria componente Radio
studiovisual/base-theme pull request #20
Opened 2023-12-07 13:22 UTC by jeffersonrucustudiovisual

# Radio

Componente é responsável por criar inputs do tipo radio em HTML

## Utilização

   ```blade
   <x-radio></x-radio>
   ```

   OU

  ```blade
   <x-radio />
  ```

## Parâmetros

Não há parâmetros disponíveis para esse componente.

## Exemplo

   ```blade
      <x-radio id="my-id" name="option-name" value="option-01"> Default </x-radio>
   ```

   OU

   ```blade
      <x-radio id="my-id" name="option-name" value="option-01" />
   ```

2023-12-07 17:05 UTC, tiagopapile commented on docs/components/README.md
> +[Radio](./readio/README.md) - Exibe um input do tipo radio
Nome da pasta está errado.

2023-12-07 17:06 UTC, tiagopapile commented on docs/components/radio/README.md
> +## Exemplo
Vamos passar esse título para o plural nas documentações.

2023-12-07 17:08 UTC, tiagopapile commented on resources/views/components/forms/radio.blade.php
> +  <input type="radio"
Adicionar a class 'radio__input'.

2023-12-08 01:45 UTC, jeffersonrucustudiovisual commented on docs/components/radio/README.md
> +## Exemplo
Ajuste realizado [f7a1e4b](https://github.com/studiovisual/base-theme/pull/20/commits/f7a1e4be2ac39c08de780a6c305089462f26e205)

2023-12-08 01:48 UTC, jeffersonrucustudiovisual commented on resources/views/components/forms/radio.blade.php
> +  <label for="{{ $attributes['id'] ?? '' }}"> {{ $slot }} </label>
Ajuste realizado [3bcb17f](https://github.com/studiovisual/base-theme/pull/20/commits/3bcb17f04841f27a8d8eeec0b82f4062e43a47e6)

2023-12-08 15:36 UTC, tiagopapile commented on resources/views/components/forms/radio.blade.php
> +  <input class="radio__input" type="radio"
Essa classe aqui está quebrando o componente não aplicando as demais classes.

2023-12-08 15:38 UTC, tiagopapile commented on resources/views/components/forms/radio.blade.php
> +<div class="radio flex items-center gap-8 my-4">
Não daria pra fazer o mesmo que o checkbox de usar o label como wrapper no lugar da div?

2023-12-08 15:38 UTC, tiagopapile requested changes
Verificar comentários.

2023-12-11 12:35 UTC, jeffersonrucustudiovisual commented on resources/views/components/forms/radio.blade.php
> +  <input class="radio__input" type="radio"
Ajuste realizado [e849690](https://github.com/studiovisual/base-theme/pull/20/commits/e849690088a796463b6f77976b17706dd5c354fa)

2023-12-11 12:35 UTC, jeffersonrucustudiovisual commented on resources/views/components/forms/radio.blade.php
> +<div class="radio flex items-center gap-8 my-4">
Deu sim, ajuste realizado [77ff5e4](https://github.com/studiovisual/base-theme/pull/20/commits/77ff5e41c6730584d0655dc84ae76f542f4bff08)

2023-12-12 12:32 UTC, tiagopapile approved these changes
Aprovado

2023-12-12 12:32 UTC, merged