tb-21 Adiciona componente Alert
studiovisual/base-theme pull request #22
Opened 2023-12-07 13:42 UTC by aresnoname

2023-12-13 20:10 UTC, tiagopapile commented on resources/views/layouts/only-content.blade.php
Sugestão: alterar o nome desse arquivo para canvas.blade.php

2023-12-13 20:13 UTC, tiagopapile commented on app/View/Components/Common/Alert.php
> +        string $base = null,
Esse parâmetro não está fazendo muito sentido. Nesse momento vamos deixar os componentes mais fixos de acordo com o layout, sem necessidade de parametrizar tanto. Além disso apenas passando as classes já seria possível mudar o estilo, sem necessidade de um parâmetro específico para isso.

2023-12-13 20:15 UTC, tiagopapile commented on app/View/Components/Common/Alert.php
> +    public string $base = 'flex gap-8 items-center rounded border border-solid';
Estamos utilizando o nome $classes para guardar as classes padrões do componente.

2023-12-13 20:25 UTC, tiagopapile commented on app/View/Components/Common/Alert.php
> +    ) {
Aqui pode ter algumas melhorias:

- As propriedades $this->type e $this->size podem guardar os valores recebidos via parâmetros, assim eles ficam disponíveis no front, podendo ser útil em algum momento.
- Concatenar todas as classes de parâmetros diretamente no controller e não no front

2023-12-13 20:29 UTC, tiagopapile commented on resources/images/icons/alert-error.svg
Vamos usar os ícones que foram exportados. O ideal é que a cor dele seja aplicada via classes.

Isso vale para todos os ícones utilizados no alerta.

Obs.: Remover esses arquivos de ícones que não serão mais utilizados.

2023-12-13 20:30 UTC, tiagopapile requested changes
Verificar comentários.

2023-12-13 22:31 UTC, aresnoname commented on resources/views/layouts/only-content.blade.php
Foi ajustado conforme o orientado

2023-12-13 22:32 UTC, aresnoname commented on app/View/Components/Common/Alert.php
> +        string $base = null,
esse parâmetro foi removido

2023-12-13 22:32 UTC, aresnoname commented on app/View/Components/Common/Alert.php
> +    public string $base = 'flex gap-8 items-center rounded border border-solid';
Foi ajustado conforme o orientado

2023-12-13 22:32 UTC, aresnoname commented on app/View/Components/Common/Alert.php
> +    ) {
foi ajustado conforme o orientado

2023-12-13 22:33 UTC, aresnoname commented on resources/images/icons/alert-error.svg
Foi ajustado conforme o orientado

2023-12-13 22:36 UTC, aresnoname commented on app/View/Components/Common/Alert.php
> +        $this->classes .= ' ' . ($this->types[$type] ?? $this->types['info']) . ' '
Foi feito uma quebra de linha para ter que evitar colocar `phpcs:ignore`

2023-12-13 22:37 UTC, aresnoname commented on app/View/Composers/Footer.php
> +            'social_media' => (!empty($acf_footer['display_social_media'])
mesmo caso do de cima, foi feito uma quebra de linha para evitar usar `phpcs:ignore`

2023-12-14 00:06 UTC, tiagopapile commented on app/View/Components/Common/Alert.php
> +                                    . ($this->sizes[$size] ?? $this->sizes['default']);
Sugestão: pra ficar melhor e passar no lint, poderia fazer em duas linhas.

`$this->classes .= ' ' . ($this->types[$type] ?? $this->types['info']);`
`$this->classes .= ' ' . ($this->sizes[$size] ?? $this->sizes['default']);`

2023-12-14 00:08 UTC, tiagopapile requested changes
Verificar comentários.

2023-12-14 01:01 UTC, aresnoname commented on app/View/Components/Common/Alert.php
> +                                    . ($this->sizes[$size] ?? $this->sizes['default']);
Foi ajustado conforme o orientado

2023-12-14 11:41 UTC, merged