tb-34 Adiciona componente Most Read
studiovisual/base-theme pull request #36
Opened 2023-12-15 22:42 UTC by aresnoname

# Most Read

Componente exibe postagens que forem passadas via parâmetro.

## Utilização

   ```blade
   <x-most-read> </most-read>
   ```

## Parâmetros

### posts &nbsp; `object`

- Recebe as postagens do wordpress em forma de objeto para serem exibidas.

## Exemplo

  ```php
  $posts = new \WP_Query($args)
  ```

   ```blade
   <x-most-read :posts="$posts"></most-read>
   ```

<p align="right">(<a href="../README.md">voltar</a>)</p>

2023-12-18 13:01 UTC, tiagopapile commented on resources/views/components/navigation/most-read.blade.php
> +                    <a href="{{ get_permalink() }}" class="block ml-12 text-lg absolute-center text-neutral-700 hover:text-purple transition-colors">
Utilizar a diretiva @permalink

2023-12-18 13:01 UTC, tiagopapile commented on resources/views/components/navigation/most-read.blade.php
> +                        {{ the_title() }}
Utilizar a diretiva @title

2023-12-18 13:02 UTC, tiagopapile commented on resources/views/components/navigation/most-read.blade.php
> +<div>
Faltou adicionar os atributos.

2023-12-18 13:06 UTC, tiagopapile commented on resources/styles/common/utilities.scss
> +.absolute-center {
Alterar para .absolute-center-y, já que centraliza verticalmente.

2023-12-18 13:06 UTC, tiagopapile requested changes
Verificar comentários

2023-12-18 15:13 UTC, aresnoname commented on resources/views/components/navigation/most-read.blade.php
> +                    <a href="{{ get_permalink() }}" class="block ml-12 text-lg absolute-center text-neutral-700 hover:text-purple transition-colors">
Foi ajustado

2023-12-18 15:13 UTC, aresnoname commented on resources/views/components/navigation/most-read.blade.php
> +                        {{ the_title() }}
Foi ajustado

2023-12-18 15:16 UTC, aresnoname commented on resources/views/components/navigation/most-read.blade.php
> +<div>
Caso fosse utilizado `<x-most-read class="suas-classes" aria-label="seu-texto"></x-most-read>` iria funcionar também,
apenas classes dentro do controller que não iria funcionar, mas no momento também não tinha nenhuma.

Mas foi ajustado conforme conversamos, adicionado o `$atributos` e o componente inicia com `section`

2023-12-18 15:16 UTC, aresnoname commented on resources/styles/common/utilities.scss
> +.absolute-center {
Foi ajustado

2023-12-18 15:18 UTC, tiagopapile commented on app/View/Components/Navigation/MostRead.php
> +    public string $classes = '';
Pode remover se não for utilizar.

2023-12-18 15:19 UTC, tiagopapile commented on resources/views/components/navigation/most-read.blade.php
Falta seguir o padrão BEM para adicionar as classes aos elementos, como no exemplo da documentação de componente.

2023-12-18 15:21 UTC, tiagopapile requested changes
Verificar comentários.

2023-12-18 15:50 UTC, aresnoname commented on app/View/Components/Navigation/MostRead.php
> +    public string $classes = '';
Foi removido por não ser utilizado

2023-12-18 15:51 UTC, aresnoname commented on resources/views/components/navigation/most-read.blade.php
Padrão `BEM` adicionado nos componentes:
* Most Read
* Scroll To Top
* Social Media
* Alert

2023-12-18 16:43 UTC, tiagopapile commented on resources/views/components/common/alert.blade.php
> +<div {{ $attributes->merge(['class' => $classes . ' alert']) }}>
Só para mantermos o padrão, coloca essa classe no início.

2023-12-18 16:43 UTC, tiagopapile commented on resources/views/components/common/alert.blade.php
> +      @svg('images.icons.' . $icon, 'alert__icon path-current', 'alert-icon') {{$message}}
Falta espaço no `{{$message}}`

2023-12-18 16:44 UTC, tiagopapile commented on resources/views/components/navigation/most-read.blade.php
> +    @if ($posts->have_posts())
Esse if pode ser passado para o início, para não ficar uma section vazia.

2023-12-18 16:46 UTC, tiagopapile commented on resources/views/components/navigation/most-read.blade.php
> +    @if ($posts->have_posts())
Utilizar essa diretiva https://log1x.github.io/sage-directives-docs/usage/wordpress.html#hasposts

2023-12-18 16:47 UTC, tiagopapile commented on resources/views/components/navigation/most-read.blade.php
> +            @while ($posts->have_posts())
O while e a linha abaixo podem ser substituídos por https://log1x.github.io/sage-directives-docs/usage/wordpress.html#posts

2023-12-18 16:48 UTC, tiagopapile commented on resources/views/components/navigation/scroll-to-top.blade.php
> +<a {{ $attributes->merge(['class' => $classes . ' scroll-to-top']) }}>
Só para mantermos o padrão, coloca essa classe no início.

2023-12-18 16:48 UTC, tiagopapile commented on resources/views/components/navigation/social-media.blade.php
> +    <div {{ $attributes->merge(['class' => $classes . ' social-media']) }}>
Só para mantermos o padrão, coloca essa classe no início.

2023-12-18 16:49 UTC, tiagopapile requested changes
Verificar comentários.

2023-12-18 17:53 UTC, aresnoname commented on resources/views/components/common/alert.blade.php
> +<div {{ $attributes->merge(['class' => $classes . ' alert']) }}>
Foi ajustado

2023-12-18 17:53 UTC, aresnoname commented on resources/views/components/common/alert.blade.php
> +      @svg('images.icons.' . $icon, 'alert__icon path-current', 'alert-icon') {{$message}}
Foi ajustado

2023-12-18 17:53 UTC, aresnoname commented on resources/views/components/navigation/scroll-to-top.blade.php
> +<a {{ $attributes->merge(['class' => $classes . ' scroll-to-top']) }}>
Foi ajustado

2023-12-18 17:54 UTC, aresnoname commented on resources/views/components/navigation/social-media.blade.php
> +    <div {{ $attributes->merge(['class' => $classes . ' social-media']) }}>
Foi ajustado

2023-12-18 20:57 UTC, aresnoname commented on resources/views/components/navigation/most-read.blade.php
> +    @if ($posts->have_posts())
Foi ajustado conforme o orientado.

Obs:
* Para que fosse possível utilizar o `sage directives` foi necessário passar os posts para view do componente com a variável `$query`, pois a diretiva `hasposts` e `posts` pegam os posts automaticamente de `$query`.

* Pra não ficar contra intuitivo o componente recebe as postagens pelo parâmetro `$posts` mas envia para view através de `$query`

2023-12-18 20:58 UTC, aresnoname commented on resources/views/components/navigation/most-read.blade.php
> +            @while ($posts->have_posts())
foi ajustado conforme o orientado, verificar comentário a cima.

2023-12-19 12:59 UTC, tiagopapile commented on tests/unit/components/MostReadTest.php
Acho que esse teste não seria válido, pois não está puxando os posts via WP_Query.

Modifica para WP_Query para trazer posts reais.

2023-12-19 12:59 UTC, tiagopapile commented on app/View/Components/Navigation/MostRead.php
> +    public function __construct(object $posts = new \stdClass()) {
Trocar o nome do parâmetro para $query.

Não seria melhor o tipo do parâmentro esperado ser WP_Query?

2023-12-19 12:59 UTC, tiagopapile requested changes
Verificar comentários.

2023-12-20 18:19 UTC, aresnoname commented on app/View/Components/Navigation/MostRead.php
> +    public function __construct(object $posts = new \stdClass()) {
Foi ajustado conforme o orientado

2023-12-20 18:21 UTC, aresnoname commented on tests/unit/components/MostReadTest.php
* Removi os testes utilizando `stdClass()`

* Conforme conversamos, não foi possível utilizar a classe `WP_Query` dentro dos testes php-unit.

* Instalei a lib `WP_Mock` para tentar simular essa papel, irei deixar alguns pontos em um outro comentário.

2023-12-20 18:29 UTC, aresnoname commented on tests/unit/components/MostReadTest.php
> +     * @testdox Verifica instancia do parâmetro 'query' se é 'WP_Query'
* A lib `WP_Mock` simula a classe `WP_Query` mas ela não é exatamente o mesmo tipo...
* Por isso caso a função esteja assim `(object $query)` será reconhecido com verdadeiro.
* Mas até o momento é o melhor que deu para fazer.
* Coloquei outros testes tentar avisar caso `$query` esteja recebendo algo além de `WP_Query`.

2023-12-22 12:37 UTC, aresnoname commented on tests/unit/components/navigation/MostReadTest.php
> +        Mockery::mock('WP_Query');
* Utilizando dessa forma é possível verificar se o parâmetro está recebendo realmente o tipo `WP_Query` por esse motivo o teste foi mantido. 

* Caso altere no componente para receber `object` ou algum outro tipo, o teste irá retornar erro.

2023-12-22 12:47 UTC, tiagopapile approved these changes
Aprovado.

2023-12-22 12:48 UTC, merged