tb-8 Cria Componente Cookie Bar
studiovisual/base-theme pull request #37
Opened 2023-12-16 21:23 UTC by jeffersonrucustudiovisual

# Cookie Bar

Componente é responsável por criar popup pedindo para usuário aceitar a utilização de cookies no site

## Utilização

   ```blade
   <x-cookie-bar></x-cookie-bar>
   ```

## Parâmetros

Não há parâmetros disponíveis para esse componente.

## Exemplos

   ```blade
  <x-cookie-bar>
    Texto
  </x-cookie-bar>
   ```

<p align="right">(<a href="../README.md">voltar</a>)</p>

-------

# Visual

## 1366px
<img width="1024" alt="Screenshot 2023-12-16 at 18 18 54" src="https://github.com/studiovisual/base-theme/assets/113918065/019d17e3-ec3f-492b-bae5-c70a507c43d2">

## 768px
<img width="475" alt="Screenshot 2023-12-16 at 18 19 28" src="https://github.com/studiovisual/base-theme/assets/113918065/ca520103-d01e-4c2c-bfdf-105a01a765f2">

## 375px
<img width="228" alt="Screenshot 2023-12-16 at 18 19 50" src="https://github.com/studiovisual/base-theme/assets/113918065/fab36927-4c65-4ed1-a746-02554cc126b0">

## Admin
<img width="1038" alt="Screenshot 2023-12-16 at 18 20 56" src="https://github.com/studiovisual/base-theme/assets/113918065/59b48d7a-d664-46e7-8221-8a1b929c34f4">

2023-12-16 21:59 UTC, richarditokazo approved these changes
Está OK

2023-12-16 22:21 UTC, tiagopapile commented on app/Options/General.php
> +                    ->addWysiwyg('text', [
Array não está alinhado.

2023-12-16 22:24 UTC, tiagopapile commented on app/Providers/ThemeServiceProvider.php
> +        Blade::component('cookie-bar', \App\View\Components\CookieBar::class);
Colocar dentro de alguma outra pasta. Podemos alinhar em qual ficaria melhor.

2023-12-16 22:27 UTC, tiagopapile commented on app/View/Components/CookieBar.php
> +        bundle('cookie-bar')->enqueue();
Passar esse enqueue para dentro do método render.

2023-12-16 22:28 UTC, tiagopapile commented on resources/scripts/components/cookie-bar.js
> + * Controls light/dark mode on the website.
Descrição não corresponde.

2023-12-16 22:32 UTC, tiagopapile commented on resources/scripts/components/cookie-bar.js
> +    this.acceptButton = this.querySelector('[data-js="accept-cookie"]');
Esse atributo não está muito claro. Poderia obter esse elemento via classe mesmo, ou usar algum atributo mais específico.

Caso seja atributo, não precisa ser um atributo com valor necessariamente, exemplo:

`this.acceptButton = this.querySelector('[accept-cookie]');`

2023-12-16 22:33 UTC, tiagopapile commented on resources/scripts/components/cookie-bar.js
> +      this.store = localStorage;
Essa variável precisa ser definida fora do try primeiro.

2023-12-16 22:34 UTC, tiagopapile commented on resources/scripts/components/cookie-bar.js
> +    if(this.acceptButton)
Pode resumir essa verificação utilizando a linha abaixo para remover o if:

`this.acceptButton?.addEventListener('click', () => this.accept());`

2023-12-16 22:36 UTC, tiagopapile commented on resources/scripts/components/cookie-bar.js
> +    const acceptCookie = Boolean(this.store.getItem('accept-cookie'));
A key 'accept-cookie' está se repetindo com frequência no código, o ideal é que seja definido numa variável para ficar fácil a manutenção.

2023-12-16 22:39 UTC, tiagopapile commented on resources/scripts/components/cookie-bar.js
> +      setTimeout(() => {
Não entendi muito bem o porque do timeout. A barra pode vir escondida por padrão e ser ativada caso não tenha sido gravada a opção, sem necessidade de se utilizar timeout.

2023-12-16 22:41 UTC, tiagopapile commented on resources/scripts/components/cookie-bar.js
> +  activeBar() {
O nome desse método pode ser apenas active(), assim mantendo o padrão das demais.

2023-12-16 22:42 UTC, tiagopapile commented on resources/scripts/components/cookie-bar.js
> +  inactiveBar() {
O nome desse método pode ser apenas inactive(), assim mantendo o padrão das demais.

2023-12-16 22:44 UTC, tiagopapile commented on resources/scripts/components/cookie-bar.js
> +    this.store.setItem('accept-cookie', 'true');
Utilizar `this.store?` para caso ele não seja definido, não quebrar o código.

2023-12-16 22:44 UTC, tiagopapile commented on resources/scripts/components/cookie-bar.js
> +    this.store.setItem('accept-cookie', 'false');
Utilizar `this.store?` para caso ele não seja definido, não quebrar o código.

2023-12-16 22:46 UTC, tiagopapile commented on resources/styles/components/cookie-bar.scss
Isso pode ser feito diretamente no elemento via classes do tailwind, em caso de dúvidas pergunta lá no grupo.

2023-12-16 22:47 UTC, tiagopapile commented on resources/views/components/cookie-bar.blade.php
> +
Linha em branco sobrando.

2023-12-16 22:48 UTC, tiagopapile commented on resources/views/components/cookie-bar.blade.php
> +      <x-button class="m-8 min-w-[90px]" size="sm" data-js="accept-cookie">Aceitar</x-button>
É necessário definir um tamanho mínimo para o botão?

2023-12-16 22:50 UTC, tiagopapile requested changes
Verificar comentários.

2023-12-18 23:49 UTC, jeffersonrucustudiovisual commented on app/Options/General.php
> +                    ->addWysiwyg('text', [
Ajuste realizado [e82f80f](https://github.com/studiovisual/base-theme/pull/37/commits/e82f80f34338602540623cd2b204c3359b4dc33b)

2023-12-19 00:03 UTC, jeffersonrucustudiovisual commented on app/Providers/ThemeServiceProvider.php
> +        Blade::component('cookie-bar', \App\View\Components\CookieBar::class);
Ajuste realizado [ceb2683](https://github.com/studiovisual/base-theme/pull/37/commits/ceb26831626661edfc5dfc6d5b9c3606be0070a0)

2023-12-19 00:04 UTC, jeffersonrucustudiovisual commented on app/View/Components/CookieBar.php
> +        bundle('cookie-bar')->enqueue();
Ajuste realizado [4fe5b6e](https://github.com/studiovisual/base-theme/pull/37/commits/4fe5b6ec618d25cf1321986734b7d71808976538)

2023-12-19 00:06 UTC, jeffersonrucustudiovisual commented on resources/scripts/components/cookie-bar.js
> + * Controls light/dark mode on the website.
Ajuste realizado [47e8de5](https://github.com/studiovisual/base-theme/pull/37/commits/47e8de52c35f3d56ca04b14a7d578812e3b3e0c3)

2023-12-19 00:10 UTC, jeffersonrucustudiovisual commented on resources/scripts/components/cookie-bar.js
> +    this.acceptButton = this.querySelector('[data-js="accept-cookie"]');
A ideia era isolar os identificadores utilizados no JS para não correr o risco de alguém apagar, etc. Assim, ficaria bem evidente que aquele identificador é exclusivo para ser utilizado no JavaScript, mas utilizar apenas accept-cookie parece atender bem.

Ajuste realizado [14ad686](https://github.com/studiovisual/base-theme/pull/37/commits/14ad6863b0768a20ceea16d37903e03693a86ad6)

2023-12-19 00:12 UTC, jeffersonrucustudiovisual commented on resources/scripts/components/cookie-bar.js
> +      this.store = localStorage;
Ajuste realizado [7d57698](https://github.com/studiovisual/base-theme/pull/37/commits/7d57698b184d2f8e1ce833a8d947dea17bcad90a)

2023-12-19 00:14 UTC, jeffersonrucustudiovisual commented on resources/scripts/components/cookie-bar.js
> +    if(this.acceptButton)
Ajuste realizado [0716e3e](https://github.com/studiovisual/base-theme/pull/37/commits/0716e3e188c5d9afce55860d2220304ccffed4d5)

2023-12-19 00:17 UTC, jeffersonrucustudiovisual commented on resources/scripts/components/cookie-bar.js
> +    const acceptCookie = Boolean(this.store.getItem('accept-cookie'));
Ajuste realizado [23d02af](https://github.com/studiovisual/base-theme/pull/37/commits/23d02af3bb8d9c2b4a1cfb78000fbb3ad741d833)

2023-12-19 00:25 UTC, jeffersonrucustudiovisual commented on resources/scripts/components/cookie-bar.js
> +      setTimeout(() => {
A ideia do `timeout` seria para que o elemento surgi-se na tela depois da página carregada, sem o `timeout` ele já aparece na tela sem o efeito se surgimento, podemos removê-lo, pois acredito que esse nível de detalhe não vem ao caso do componente

### Sem Timeout
https://github.com/studiovisual/base-theme/assets/113918065/c67bd790-001a-4516-9559-cd7b36ec997d

### Com Timeout
https://github.com/studiovisual/base-theme/assets/113918065/84a3e9b1-e646-4f08-8367-455605f64db4

2023-12-19 00:27 UTC, jeffersonrucustudiovisual commented on resources/scripts/components/cookie-bar.js
> +  activeBar() {
Ajuste realizado [ea8da15](https://github.com/studiovisual/base-theme/pull/37/commits/ea8da152cd6c80c81106051253b38fbcc9ad9721)

2023-12-19 00:27 UTC, jeffersonrucustudiovisual commented on resources/scripts/components/cookie-bar.js
> +  inactiveBar() {
Ajuste realizado [ea8da15](https://github.com/studiovisual/base-theme/pull/37/commits/ea8da152cd6c80c81106051253b38fbcc9ad9721)

2023-12-19 00:29 UTC, jeffersonrucustudiovisual commented on resources/scripts/components/cookie-bar.js
> +    this.store.setItem('accept-cookie', 'true');
Ajuste realizado [bc91d9d](https://github.com/studiovisual/base-theme/pull/37/commits/bc91d9d4a6b4c586124fc92b72182c464cb5e1f9)

2023-12-19 00:29 UTC, jeffersonrucustudiovisual commented on resources/scripts/components/cookie-bar.js
> +    this.store.setItem('accept-cookie', 'false');
Ajuste realizado [bc91d9d](https://github.com/studiovisual/base-theme/pull/37/commits/bc91d9d4a6b4c586124fc92b72182c464cb5e1f9)

2023-12-19 00:29 UTC, jeffersonrucustudiovisual commented on resources/styles/components/cookie-bar.scss
Ajuste realizado [ceb2683](https://github.com/studiovisual/base-theme/pull/37/commits/ceb26831626661edfc5dfc6d5b9c3606be0070a0)

2023-12-19 00:32 UTC, jeffersonrucustudiovisual commented on resources/views/components/cookie-bar.blade.php
> +      <x-button class="m-8 min-w-[90px]" size="sm" data-js="accept-cookie">Aceitar</x-button>
Foi necessário neste caso porque, ao redimensionar a tela, em alguns momentos, o botão diminuía de tamanho a ponto de não caber o texto nele. Isso foi ocasionado pela utilização do display flex.

![image](https://github.com/studiovisual/base-theme/assets/113918065/aba60f02-942a-4c91-8c68-8c1ce24e334f)

2023-12-19 00:34 UTC, jeffersonrucustudiovisual commented on resources/views/components/cookie-bar.blade.php
> +
Ajuste realizado [288da82](https://github.com/studiovisual/base-theme/pull/37/commits/288da823e6a32c6e2ede5b38f15d17b16556cd5b)

2023-12-19 00:38 UTC, jeffersonrucustudiovisual commented on resources/views/components/cookie-bar.blade.php
Olhei o componente e só consegui pensar em adicionar a class `cookie-bar` no elemento pai e no botão, devo adicionar em mais algum filho ?

2023-12-19 13:02 UTC, tiagopapile commented on resources/scripts/components/cookie-bar.js
> +      setTimeout(() => {
Entendi o que precisa, mas isso não poderia ser feito colocando um delay na animação?

2023-12-19 13:04 UTC, tiagopapile commented on resources/views/components/cookie-bar.blade.php
> +      <x-button class="m-8 min-w-[90px]" size="sm" data-js="accept-cookie">Aceitar</x-button>
Acho que melhor do que definir o tamanho para o botão, seria ajustar o elemento de texto para que ocupe o espaço restante. Tem algumas classes que podem ajudar nisso, se não conseguir achar podemos fazer uma call pra ajustar.

2023-12-19 13:06 UTC, tiagopapile commented on resources/views/components/cookie-bar.blade.php
Adiciona no container e no elemento de texto também.

2023-12-19 13:50 UTC, jeffersonrucustudiovisual commented on resources/scripts/components/cookie-bar.js
> +      setTimeout(() => {
_Foi mantido a animação do timeout_

2023-12-19 13:57 UTC, jeffersonrucustudiovisual commented on resources/views/components/cookie-bar.blade.php
Ajuste realizado [e37e156](https://github.com/studiovisual/base-theme/pull/37/commits/e37e15622ef7b773d757a4c6d364c6f519841478)

2023-12-19 13:58 UTC, jeffersonrucustudiovisual commented on resources/views/components/cookie-bar.blade.php
> +      <x-button class="m-8 min-w-[90px]" size="sm" data-js="accept-cookie">Aceitar</x-button>
Ajuste realizado [f849d01](https://github.com/studiovisual/base-theme/pull/37/commits/f849d01997435c2b13a6fb09e9756540c83db3a4)

2023-12-19 14:00 UTC, tiagopapile approved these changes
Aprovado.

2023-12-19 14:10 UTC, merged