Feature/tb 20
studiovisual/base-theme pull request #38
Opened 2023-12-18 19:16 UTC by richarditokazo

2023-12-18 21:18 UTC, aresnoname commented on resources/views/playground/components/badge.blade.php
> +<div id="component-badge" class="div-component">
* Faltou adicionar o `id` da div no menu de navegação dos componentes no arquivo `components.blade.php`
* A ordem de navegação está sendo mantida igual a ordem dos arquivos, pois eles são carregados em sequencia.

2023-12-18 21:19 UTC, aresnoname requested changes
Verificar comentário.

2023-12-18 21:26 UTC, tiagopapile requested changes
Faltou colocar o link para a documentação do componente.

2023-12-18 21:34 UTC, richarditokazo commented on resources/views/playground/components/badge.blade.php
> +<div id="component-badge" class="div-component">
Isso será refatorado, pois não está feito da melhor maneiro, pretendo utilizar um select para fazer o scroll e fazer de forma automatica o select.

2023-12-18 21:46 UTC, aresnoname approved these changes
Por mim está aprovado

2023-12-18 23:43 UTC, jeffersonrucustudiovisual approved these changes
Tudo okay, eu só arrumaria o título do Pull Request para seguir o padrão estabelecido para o projeto.

`código-da-tarefa` + `descrição`

2023-12-19 12:42 UTC, tiagopapile approved these changes
Aprovado.

2023-12-19 12:42 UTC, merged