tb-24 Adiciona componente de paginação
studiovisual/base-theme pull request #39
Opened 2023-12-19 12:41 UTC by aresnoname

2024-01-02 18:54 UTC, tiagopapile commented on app/View/Components/Navigation/Pagination.php
> +    protected array $buttonControlTypes = [
Pode se chamar apenas `$types` para seguir o padrão dos demais componentes.

2024-01-02 19:17 UTC, tiagopapile commented on docs/components/navigation/pagination/README.md
> +Componente exibe a paginação.
Descrever um pouco mais o componente.

2024-01-02 19:20 UTC, tiagopapile commented on resources/views/archive.blade.php
> +
Linha sobrando.

2024-01-02 19:21 UTC, tiagopapile commented on resources/views/components/common/button.blade.php
> -<{{ $attributes->has('href') ? 'a' : 'button' }} {{ $attributes->merge(['class' => 'button ' . $classes]) }}>
Algum motivo para mudar de `has` para `get`?

2024-01-02 20:47 UTC, tiagopapile commented on app/View/Components/Navigation/Pagination.php
> +        'default' => '!p-8',
Não utilizar o nome `default`. Poderia ser `square`.

2024-01-02 20:57 UTC, tiagopapile commented on app/View/Components/Navigation/Pagination.php
A lógica geral está muito complexa e diferente dos demais componentes. Sugiro alinharmos sobre essa parte.

2024-01-02 20:58 UTC, tiagopapile requested changes
A lógica geral está muito complexa e diferente dos demais componentes. Sugiro alinharmos sobre essa parte.

2024-01-12 01:28 UTC, aresnoname commented on app/View/Components/Navigation/Pagination.php
> +    protected array $buttonControlTypes = [
Foi ajustado para `$types`

2024-01-12 01:29 UTC, aresnoname commented on docs/components/navigation/pagination/README.md
> +Componente exibe a paginação.
Foi ajustado
* `Componente para exibir a paginação de páginas padrão ou customizadas.`

2024-01-12 01:30 UTC, aresnoname commented on resources/views/archive.blade.php
> +
Componente foi removido da view `archive` pois agora é possível utilizar custom query

2024-01-12 01:36 UTC, aresnoname commented on resources/views/components/common/button.blade.php
> -<{{ $attributes->has('href') ? 'a' : 'button' }} {{ $attributes->merge(['class' => 'button ' . $classes]) }}>
É porque não conseguir fazer algo assim em componentes personalizados:
 `<x-button {{ ($x == 2) ? 'href=' . $value : '' }} />`

Ai o componente button utilizando `get` quando é passado um `href="" ` (em branco) ele virá um `button ` e é possível utilizar `disabled`

Se utilizar `has` e passar um `href=""`  (em branco) ele continua virando uma ancora `<a href="">` e não é possível utilizar `disabled ` sem JS

2024-01-12 01:37 UTC, aresnoname commented on app/View/Components/Navigation/Pagination.php
> +        'default' => '!p-8',
Foi ajustado para `square`.

Tem alguma sugestão para substituir type `Text` ? não consegui pensar em nada rsrs

2024-01-12 01:39 UTC, aresnoname commented on app/View/Components/Navigation/Pagination.php
Conforme alinhamos, tentei melhorar a lógica.
Por conta do mobile foi preciso aplicar uma certa formula na parte das páginas, tentei fazer o menos complexo que consegui.

2024-01-12 02:14 UTC, aresnoname commented on composer.json
> +    "test-debug": [
Adicionei esse comando pois durante o desenvolvimento dos testes unitários, o PHP Unit estava enviando alertas `OK, but...` e não estava mostrando qual era o problema.

Pesquisando um pouco vi que tinha que adicionar `--display-warnings` mas ele não funciona com `--testdox`, então adicionei esse comando.

2024-01-12 02:18 UTC, aresnoname commented on resources/views/components.blade.php
> -      padding: 16px;
Foi necessário remover esse padding pois o componente de paginação fica certinho no container do mobile.

2024-01-12 16:47 UTC, tiagopapile commented on app/View/Components/Navigation/Pagination.php
> +        'default' => '!p-8',
Tudo bem ser `text` mesmo.

2024-01-12 17:38 UTC, tiagopapile commented on resources/views/components/navigation/pagination.blade.php
> +      <x-button class="{{ $classes['control'] }}"
Colocar class numa nova linha e adicionar uma identação em todos os atributos.

2024-01-12 17:39 UTC, tiagopapile commented on resources/views/components/navigation/pagination.blade.php
> +      <x-button class="{{ $classes['control'] . 'order-last' }}"
Colocar class numa nova linha e adicionar uma identação em todos os atributos.

2024-01-12 17:40 UTC, tiagopapile commented on resources/views/components/navigation/pagination.blade.php
> +    <x-button class="{{ $classes['control'] }}"
Colocar class numa nova linha e adicionar uma identação em todos os atributos.

2024-01-12 17:40 UTC, tiagopapile commented on resources/views/components/navigation/pagination.blade.php
> +        <x-button class="{{ $classes['page'] }}"
Colocar class numa nova linha e adicionar uma identação em todos os atributos.

2024-01-12 17:40 UTC, tiagopapile commented on resources/views/components/navigation/pagination.blade.php
> +    <x-button class="{{ $classes['control'] }}"
Colocar class numa nova linha e adicionar uma identação em todos os atributos.

2024-01-12 17:41 UTC, tiagopapile requested changes
Verificar comentários.

2024-01-12 17:53 UTC, aresnoname commented on resources/views/components/navigation/pagination.blade.php
> +      <x-button class="{{ $classes['control'] }}"
Foi ajustado

2024-01-12 17:53 UTC, aresnoname commented on resources/views/components/navigation/pagination.blade.php
> +      <x-button class="{{ $classes['control'] . 'order-last' }}"
Foi ajustado

2024-01-12 17:53 UTC, aresnoname commented on resources/views/components/navigation/pagination.blade.php
> +    <x-button class="{{ $classes['control'] }}"
Foi ajustado

2024-01-12 17:53 UTC, aresnoname commented on resources/views/components/navigation/pagination.blade.php
> +        <x-button class="{{ $classes['page'] }}"
Foi ajustado

2024-01-12 17:54 UTC, aresnoname commented on resources/views/components/navigation/pagination.blade.php
> +    <x-button class="{{ $classes['control'] }}"
Foi ajustado

2024-01-12 18:09 UTC, richarditokazo approved these changes
Está OK.

2024-01-12 19:30 UTC, tiagopapile approved these changes
OK.

2024-01-12 19:32 UTC, merged