tb-23 Adiciona componente Bread Crumb
studiovisual/base-theme pull request #41
Opened 2023-12-22 12:26 UTC by aresnoname

# Bread Crumb

Exibe um caminho que foi percorrido até chegar na categoria ou postagem atual

## Utilização

   ```blade
   <x-bread-crumb></x-bread-crumb>
   ```

## Parâmetros

### maxDepth &nbsp; `integer`

- **1 a 9999999 -** Controla a quantidade de categorias pais que iram aparecer

### showLastPage &nbsp; `string`

- **true -** Mostra o nome da postagem no final do bread crumb
- **false -** Não mostra o nome da postagem no bread crumb

### showAllCategories &nbsp; `string`

- **true -** Caso houver mais de uma categoria na postagem, irá mostrar todas e inclui seus pais
- **false -** Mostra apenas a primeira categoria encontrada

## Exemplos

   ```blade
  <x-bread-crumb maxDepth="2" showLastPage="false" showAllCategories="False"></x-bread-crumb>
   ```

2024-01-09 13:03 UTC, tiagopapile commented on docs/components/navigation/bread-crumb/README.md
> +- **1 a 9999999 -** Controla a quantidade de categorias pais que iram aparecer
Corrigir texto: irão aparecer.

Dúvida: Esse parâmetro leva em consideração a Home e a página em exibição atualmente? Seria bom deixar mais claro na documentação.

2024-01-09 13:05 UTC, tiagopapile commented on docs/components/navigation/bread-crumb/README.md
> +### showAllCategories &nbsp; `string`
Não entendi esse parâmetro. Parece entrar em conflito com o `maxDepth`.

2024-01-09 13:06 UTC, tiagopapile commented on app/View/Components/Navigation/BreadCrumb.php
> +    public string $showLastPage = 'false';
Variável precisa ser do tipo `boolean`, foi declarada como `string`.

2024-01-09 13:12 UTC, tiagopapile commented on app/View/Components/Navigation/BreadCrumb.php
> +        $crumb_category = get_category($items['id']);
Não é possível verificar se é uma categoria antes de ter que usar o `get_category`?

2024-01-09 13:17 UTC, tiagopapile commented on resources/views/components/navigation/bread-crumb.blade.php
> +        @foreach ($breadCrumb as $key => $crumb)
Não precisa declarar a `$key` se ela não vai ser utilizada.

2024-01-09 13:18 UTC, tiagopapile commented on resources/views/components/navigation/bread-crumb.blade.php
> +    <nav aria-label="Breadcrumb" class="flex gap-4 items-center">
- Faltou o padrão BEM
- Faltou os `$attributes`

2024-01-09 13:19 UTC, tiagopapile commented on resources/views/components/navigation/bread-crumb.blade.php
> +            @if ($loop->last)
Isso pode ser o else da condição acima.

2024-01-09 13:20 UTC, tiagopapile commented on resources/views/components/navigation/bread-crumb.blade.php
> +                <a aria-current="{{(!empty($crumb['url'])) ? 'category' : 'page'}}" class="py-[2px] px-[6px] text-sm rounded-[4px] text-neutral-900">
Faltou espaço ao utilizar `{{ }}`.

2024-01-09 13:22 UTC, tiagopapile commented on resources/views/components/navigation/bread-crumb.blade.php
> +            @if (!$loop->last)
Não seria melhor utilizar a diretiva @class para adicionar as classes e escrever a tag a somente uma vez?

Qualquer dúvida de como utilizar pode me chamar.

2024-01-09 13:22 UTC, tiagopapile requested changes
- Breadcrumb é uma palavra única, necessário corrigir
- Verificar comentários

2024-01-09 18:58 UTC, aresnoname commented on docs/components/navigation/bread-crumb/README.md
> +### showAllCategories &nbsp; `string`
Caso o post tenha mais de 2 categorias e `showAllCategorias` seja true, irá aparecer no breadcrumb essas 2x categorias + seus parents.

A lib `log1x/crumb` por padrão também faz isso, ela exibe todas as categorias que a postagem tiver.

Já `maxDepth` irá controlar quantos parentes dessas categorias serão exibidos.

2024-01-09 19:01 UTC, aresnoname commented on app/View/Components/Navigation/BreadCrumb.php
> +    public string $showLastPage = 'false';
Se eu definir elas como boolean, no parametro do componente só será aceito como boolean se passar usando `:` por exempo.. `:showLastPage="true"`

Defino como boolean mesmo ?

2024-01-09 20:05 UTC, aresnoname commented on app/View/Components/Navigation/BreadCrumb.php
> +        $crumb_category = get_category($items['id']);
Eu dei uma pesquisada e não achei uma forma ideal para fazer isso.
`is_category` verifica se a página atual é uma categoria, não se aplicaria a o uso necessário.

`get_term` daria para verificar se é uma categoria, mas ele faria uma consulta ao banco de dados, depois fazendo outra consulta ao chamar get_category.

Você acha que compensa verificar utilizando `get_term` ?

2024-01-09 20:40 UTC, aresnoname commented on docs/components/navigation/bread-crumb/README.md
> +- **1 a 9999999 -** Controla a quantidade de categorias pais que iram aparecer
Texto corrigido e foi melhorado a descrição.

o `maxDepth` não contabiliza a página home e a página da postagem atual.

2024-01-09 20:41 UTC, aresnoname commented on app/View/Components/Navigation/BreadCrumb.php
> +        foreach ($build as $key => $items) {
Na real seria sim, acho que diminuiria o numero de if's durante o loop.

Foi ajustado, o loop agora se mantem apenas com as categorias.

2024-01-09 20:42 UTC, aresnoname commented on resources/views/components/navigation/bread-crumb.blade.php
> +        @foreach ($breadCrumb as $key => $crumb)
Foi ajustado

2024-01-09 20:42 UTC, aresnoname commented on resources/views/components/navigation/bread-crumb.blade.php
> +    <nav aria-label="Breadcrumb" class="flex gap-4 items-center">
Foi ajustado

2024-01-09 20:43 UTC, aresnoname commented on resources/views/components/navigation/bread-crumb.blade.php
> +            @if ($loop->last)
precisei manter essa condição para utilizar junto com `@class`

2024-01-09 20:43 UTC, aresnoname commented on resources/views/components/navigation/bread-crumb.blade.php
> +                <a aria-current="{{(!empty($crumb['url'])) ? 'category' : 'page'}}" class="py-[2px] px-[6px] text-sm rounded-[4px] text-neutral-900">
Foi ajustado

2024-01-09 20:45 UTC, aresnoname commented on resources/views/components/navigation/bread-crumb.blade.php
> +            @if (!$loop->last)
Não conhecia essa diretiva, muito interessante.
Refatorei a view utilizando ela.

2024-01-10 12:19 UTC, tiagopapile commented on app/View/Components/Navigation/BreadCrumb.php
> +    public string $showLastPage = 'false';
Sim, é o mais correto.

2024-01-10 12:21 UTC, tiagopapile commented on app/View/Components/Navigation/BreadCrumb.php
> +        $crumb_category = get_category($items['id']);
Não compensa, minha dúvida era se no item do array já não tinha essa informação de alguma forma. Se não tem mesmo, está correto da forma como foi feito.

2024-01-10 12:23 UTC, tiagopapile commented on docs/components/navigation/bread-crumb/README.md
> +### showAllCategories &nbsp; `string`
2 categorias da mesma hierarquia ou 2 categorias diferentes?

2024-01-10 12:33 UTC, aresnoname commented on docs/components/navigation/bread-crumb/README.md
> +### showAllCategories &nbsp; `string`
Se `showAllCategorias` for `true` pega 2 ou mais categorias diferentes.
e o `maxDepth` controla quantos parentes irão ser exibidos de cada uma dessas categorias.

2024-01-10 14:37 UTC, aresnoname commented on app/View/Components/Navigation/BreadCrumb.php
> +    public string $showAllCategories = 'false';
Foi ajustado para `boolean`

2024-01-10 14:40 UTC, aresnoname commented on app/View/Components/Navigation/BreadCrumb.php
> +        $crumb_category = get_category($items['id']);
Nos items do array só vem `ID, label, url`

Essa parte do código, não foi alterada

2024-01-10 18:39 UTC, tiagopapile requested changes
Verificar comentários.

2024-01-10 21:22 UTC, aresnoname commented on resources/views/components/navigation/breadcrumb.blade.php
> +    <nav {{ $attributes }} class="breadcrumb flex gap-4 items-center">
Foi ajustado

2024-01-10 21:22 UTC, aresnoname commented on app/View/Components/Navigation/Breadcrumb.php
> +    public bool $showCurrentPost = true;
Foi ajustado, coloquei $showCurrentItem

2024-01-10 21:24 UTC, aresnoname commented on app/View/Components/Navigation/Breadcrumb.php
> +        // First item (Page Home)
foi ajustado, home e ultima página são armazenadas em variáveis no início e adicionadas ao array no final.
também armazenei com chave os itens durante o loop, assim não é necessário fazer a operação para remover duplicatas

2024-01-12 16:40 UTC, tiagopapile commented on docs/components/navigation/breadcrumb/README.md
> +### maxHierarchyDepth &nbsp; `integer`
Coloca o tipo como no controller: int.

2024-01-12 16:41 UTC, tiagopapile commented on docs/components/navigation/breadcrumb/README.md
> +### showCurrentItem &nbsp; `boolean`
Coloca o tipo como no controller: bool.

2024-01-12 16:41 UTC, tiagopapile commented on docs/components/navigation/breadcrumb/README.md
> +### showAllCategories &nbsp; `boolean`
Coloca o tipo como no controller: bool.

2024-01-12 16:44 UTC, tiagopapile requested changes
Verificar comentários.

2024-01-12 17:09 UTC, aresnoname commented on docs/components/navigation/breadcrumb/README.md
> +### showCurrentItem &nbsp; `boolean`
Foi ajustado

2024-01-12 17:09 UTC, aresnoname commented on docs/components/navigation/breadcrumb/README.md
> +### showAllCategories &nbsp; `boolean`
Foi ajustado

2024-01-12 17:09 UTC, aresnoname commented on resources/views/components/navigation/breadcrumb.blade.php
> +            <a {{ !empty($crumb['url']) ? 'href=' . $crumb['url'] : '' }} aria-current="{{ !empty($crumb['url']) ? 'category' : 'page' }}" @class([
Foi ajustado

2024-01-12 17:27 UTC, tiagopapile approved these changes
OK.

2024-01-12 17:27 UTC, merged