tb-33 Cria Componente Card Featured
studiovisual/base-theme pull request #42
Opened 2023-12-26 12:41 UTC by jeffersonrucustudiovisual

# Card Featured

Componente de card para posts com imagem destaque

## Utilização

   ```blade
   <x-card-featured></x-card-featured>
   ```

## Parâmetros

### post &nbsp; `object || int`

- Objeto do post ou ID do post

### size &nbsp; `string`

- **sm -**
- **md (padrão) -**
- **lg -**

## Exemplo

  ```blade
  <x-card-featured post="1"/>
  ```

## Referência

![Screenshot 2023-12-26 at 09 38 17](https://github.com/studiovisual/base-theme/assets/113918065/8ad8acdb-6b09-4beb-aa86-f06aaa3ad40f)

<p align="right">(<a href="../README.md">voltar</a>)</p>

2024-01-02 18:07 UTC, tiagopapile commented on app/View/Components/Card/CardFeatured.php
> +    public function __construct(WP_Post|int|false $post = false, string $size = 'md') {
False não é um tipo de variável.
Ela pode ser apenas WP_Post|int e ter seu valor padrão 0.

2024-01-02 18:07 UTC, tiagopapile commented on app/View/Components/Card/CardFeatured.php
> +    public $post = false;
False não é um tipo de variável.
Ela pode ser apenas WP_Post|int e ter seu valor padrão 0.

2024-01-02 18:07 UTC, tiagopapile commented on app/View/Components/Card/CardFeatured.php
> +        if (!$post) {
Verificar usando a função `empty()`.

2024-01-02 18:09 UTC, tiagopapile commented on app/View/Components/Card/CardFeatured.php
> +        $this->post            = is_object($post) ? $post : get_post($post);
Melhor verificar se é do tipo WP_Post ao invés de um objeto genérico.

2024-01-02 18:11 UTC, tiagopapile commented on app/View/Components/Card/CardFeatured.php
> +        $this->post->post_date = get_the_time('j \d\e F \d\e Y', $this->post);
Falta verificar antes se` $this->post` conseguiu retornar algum post, caso contrário todas as linhas abaixo irão apresentar erro.

2024-01-02 18:13 UTC, tiagopapile commented on app/View/Components/Card/CardFeatured.php
> +        $this->classes         = $this->sizes[$size] ?? $this->sizes['md'];
Atribuir `$size` para `$this->size` e verificar se o array `$this->sizes` contém a chave de `$this->size`.

2024-01-02 18:15 UTC, tiagopapile commented on app/View/Components/Card/CardFeatured.php
> +        $this->post->post_date = get_the_time('j \d\e F \d\e Y', $this->post);
Aqui creio que o ideal seja exibir o formato da data como definido nas opções do Wordpress, ao invés de fixo no código.

2024-01-02 18:16 UTC, tiagopapile commented on docs/components/card-featured/README.md
> +### size &nbsp; `string`
Faltou descrever os tamanhos.

2024-01-02 18:16 UTC, tiagopapile commented on docs/components/card-featured/README.md
> +### post &nbsp; `object || int`
O correto seria `WP_Post` ao invés de `object`.

2024-01-02 18:20 UTC, tiagopapile commented on resources/views/components/card/card-featured.blade.php
> +      @thumbnail($post->ID, 'full')
Pode passar apenas `$post` como primeiro parâmetro.

2024-01-02 18:21 UTC, tiagopapile commented on resources/views/components/card/card-featured.blade.php
> +    <figure class="
Acredito que falta uma cor de fundo caso por algum motivo nenhuma imagem seja exibida.

2024-01-02 18:22 UTC, tiagopapile commented on resources/views/components/card/card-featured.blade.php
> +      class="absolute top-0 left-0 w-full h-full"
Já possui a classe `.stretched-link` que adiciona o link no card todo.

2024-01-02 18:23 UTC, tiagopapile commented on resources/views/components/card/card-featured.blade.php
> +      href="{{ get_permalink($post->ID) }}"
Utilizar a diretiva https://log1x.github.io/sage-directives-docs/usage/wordpress.html#permalink

2024-01-02 18:23 UTC, tiagopapile commented on resources/views/components/card/card-featured.blade.php
> +        {{ $post->post_title }}
Utilizar a diretiva https://log1x.github.io/sage-directives-docs/usage/wordpress.html#title

2024-01-02 18:25 UTC, tiagopapile commented on resources/views/components/card/card-featured.blade.php
> +      <p class="card-featured__date text-white text-sm">{{ $post->post_date }}</p>
Utilizar a diretiva https://log1x.github.io/sage-directives-docs/usage/wordpress.html#published.

Também é recomendado utilizar a tag `time` do HTML.

2024-01-02 18:28 UTC, tiagopapile commented on resources/views/components/card/card-featured.blade.php
> +    <div class="card-featured__content flex flex-col gap-[10px] absolute bottom-0 left-0 w-full {{ $classes['content'] }}">
Essa div e a de badges são realmente necessárias? Se possível eliminá-las para reduzir o tamanho do DOM.

2024-01-02 18:28 UTC, tiagopapile commented on resources/views/components/card/card-featured.blade.php
> +  <div
Utilizar a tag `article`.

2024-01-02 18:30 UTC, tiagopapile commented on app/View/Components/Card/CardFeatured.php
> +    protected array $sizes = [
Acredito que não seja ideal colocar uma largura máxima nos cards. Isso pode ser controlado no grid.

2024-01-03 18:51 UTC, jeffersonrucustudiovisual commented on app/View/Components/Card/CardFeatured.php
> +    public function __construct(WP_Post|int|false $post = false, string $size = 'md') {
Ajuste realizado [f79ab01](https://github.com/studiovisual/base-theme/pull/42/commits/f79ab01b0ac3e3f206ca44349c99bb0a5a511c5d)

2024-01-03 18:51 UTC, jeffersonrucustudiovisual commented on app/View/Components/Card/CardFeatured.php
> +    public $post = false;
Ajuste realizado [f79ab01](https://github.com/studiovisual/base-theme/pull/42/commits/f79ab01b0ac3e3f206ca44349c99bb0a5a511c5d)

2024-01-03 18:53 UTC, jeffersonrucustudiovisual commented on app/View/Components/Card/CardFeatured.php
> +        if (!$post) {
Ajuste realizado [b977502](https://github.com/studiovisual/base-theme/pull/42/commits/b97750290c1e5b1fd78129a0622103c4c4f5c1a2)

2024-01-03 18:59 UTC, jeffersonrucustudiovisual commented on app/View/Components/Card/CardFeatured.php
> +        $this->post            = is_object($post) ? $post : get_post($post);
Ajuste realizado [2a03dbe](https://github.com/studiovisual/base-theme/pull/42/commits/2a03dbeb6766f89ef80e179a0bd29346d43a062d)

2024-01-03 19:02 UTC, jeffersonrucustudiovisual commented on app/View/Components/Card/CardFeatured.php
> +        $this->post->post_date = get_the_time('j \d\e F \d\e Y', $this->post);
Ajuste realizado [026ebb0](https://github.com/studiovisual/base-theme/pull/42/commits/026ebb0716673d83d5ddc85ef1458d0f4d204239)

2024-01-03 19:09 UTC, jeffersonrucustudiovisual commented on app/View/Components/Card/CardFeatured.php
> +        $this->post            = is_object($post) ? $post : get_post($post);
Ajuste extra [ae5790c](https://github.com/studiovisual/base-theme/pull/42/commits/ae5790c64bd245accb9e72cd85ba9b232f7ad2b9)

2024-01-03 19:12 UTC, jeffersonrucustudiovisual commented on app/View/Components/Card/CardFeatured.php
> +        $this->post->post_date = get_the_time('j \d\e F \d\e Y', $this->post);
Ajuste realizado [4c0bb81](https://github.com/studiovisual/base-theme/pull/42/commits/4c0bb81a271cc166320826a9fa032e0f95bcd070)

2024-01-03 19:13 UTC, jeffersonrucustudiovisual commented on resources/views/components/card/card-featured.blade.php
> +  <div
Ajuste realizado [2d79d6c](https://github.com/studiovisual/base-theme/pull/42/commits/2d79d6c16845f45a41b03ed251324e8772208623)

2024-01-03 19:21 UTC, jeffersonrucustudiovisual commented on app/View/Components/Card/CardFeatured.php
> +    protected array $sizes = [
Ajuste realizado [585a177](https://github.com/studiovisual/base-theme/pull/42/commits/585a177c57842562a7e9a0ec846a59980390a2e6)

2024-01-03 19:24 UTC, jeffersonrucustudiovisual commented on app/View/Components/Card/CardFeatured.php
> +    protected array $sizes = [
Ajuste realizado [42ff1ec](https://github.com/studiovisual/base-theme/pull/42/commits/42ff1ecc6ec32270bab0c698fc0e0da343424f49)

2024-01-03 19:25 UTC, jeffersonrucustudiovisual commented on resources/views/components/card/card-featured.blade.php
> +    <div class="card-featured__content flex flex-col gap-[10px] absolute bottom-0 left-0 w-full {{ $classes['content'] }}">
A div `card-featured__content` é necessária para posicionar o conteúdo do card e a div `card-featured__badges` também para adicionar um espaçamento entre os badges

2024-01-03 19:29 UTC, jeffersonrucustudiovisual commented on resources/views/components/card/card-featured.blade.php
> +      <p class="card-featured__date text-white text-sm">{{ $post->post_date }}</p>
Ajuste realizado [c0c2fb8](https://github.com/studiovisual/base-theme/pull/42/commits/c0c2fb8ea9523f87f90ebd6fe28dffb80fdb235d)

2024-01-03 19:30 UTC, jeffersonrucustudiovisual commented on resources/views/components/card/card-featured.blade.php
> +      <p class="card-featured__date text-white text-sm">{{ $post->post_date }}</p>
Ajuste realizado [2881947](https://github.com/studiovisual/base-theme/pull/42/commits/28819477fae823d7a88a565c5e4d5fc89ef86d00)

2024-01-03 19:34 UTC, jeffersonrucustudiovisual commented on resources/views/components/card/card-featured.blade.php
> +      <p class="card-featured__date text-white text-sm">{{ $post->post_date }}</p>
Ajuste realizado [51cada0](https://github.com/studiovisual/base-theme/pull/42/commits/51cada065193b9e21cf25f4066d17c8822cf212d)

2024-01-03 19:35 UTC, jeffersonrucustudiovisual commented on resources/views/components/card/card-featured.blade.php
> +        {{ $post->post_title }}
Ajuste realizado [5d5a985](https://github.com/studiovisual/base-theme/pull/42/commits/5d5a9853b31961bec3e809f661d1114672e85d1e)

2024-01-03 19:38 UTC, jeffersonrucustudiovisual commented on resources/views/components/card/card-featured.blade.php
> +      href="{{ get_permalink($post->ID) }}"
Ajuste realizado [61b507d](https://github.com/studiovisual/base-theme/pull/42/commits/61b507d64e4b5c1453ac7c28d232eac0b0133644)

2024-01-03 19:40 UTC, jeffersonrucustudiovisual commented on resources/views/components/card/card-featured.blade.php
> +      class="absolute top-0 left-0 w-full h-full"
Ajuste realizado [398c8e9](https://github.com/studiovisual/base-theme/pull/42/commits/398c8e9d918d66fe4be7d4a8e54f5e3badfd9f26)

2024-01-03 19:42 UTC, jeffersonrucustudiovisual commented on resources/views/components/card/card-featured.blade.php
> +      @thumbnail($post->ID, 'full')
Ajuste realizado [c8dd87a](https://github.com/studiovisual/base-theme/pull/42/commits/c8dd87a6c62bc12a085859d68b7ad4771272583f)

2024-01-03 19:47 UTC, jeffersonrucustudiovisual commented on resources/views/components/card/card-featured.blade.php
> +    <figure class="
Ajuste realizado [c513576](https://github.com/studiovisual/base-theme/pull/42/commits/c513576606346877ae0ced6fd0c18228155e95d0)

2024-01-03 19:51 UTC, jeffersonrucustudiovisual commented on docs/components/card-featured/README.md
> +### size &nbsp; `string`
Ajuste realizado [df2ab33](https://github.com/studiovisual/base-theme/pull/42/commits/df2ab33bf48625196bf9b708c0c39d8621ffe57c)

2024-01-03 19:51 UTC, jeffersonrucustudiovisual commented on docs/components/card-featured/README.md
> +### post &nbsp; `object || int`
Ajuste realizado [df2ab33](https://github.com/studiovisual/base-theme/pull/42/commits/df2ab33bf48625196bf9b708c0c39d8621ffe57c)

2024-01-03 20:19 UTC, jeffersonrucustudiovisual commented on app/View/Components/Card/CardFeatured.php
> +        $this->classes         = $this->sizes[$size] ?? $this->sizes['md'];
Ajuste realizado [1099702](https://github.com/studiovisual/base-theme/pull/42/commits/1099702dded5def3bd53d55c155908fb26d68434)

2024-01-04 15:52 UTC, tiagopapile commented on app/View/Components/Card/CardFeatured.php
> +        if (empty($post)) {
Esse primeiro if acaba sendo desnecessário.

2024-01-04 15:53 UTC, tiagopapile commented on app/View/Components/Card/CardFeatured.php
> +        $this->readingTime     = reading_time($this->post->ID);
Espaó sobrando entre a variável e o valor.

2024-01-04 16:07 UTC, tiagopapile commented on resources/views/components/card/card-featured.blade.php
> +    <div class="card-featured__content flex flex-col gap-[10px] absolute bottom-0 left-0 w-full {{ $classes['content'] }}">
Usando esse css no article é possível remover a div content:

```
display: flex;
flex-direction: column;
justify-content: flex-end;
```

Após isso ajustar o z-index dos elementos.

2024-01-04 16:11 UTC, tiagopapile requested changes
Verificar comentários.

Faltou também colocar o link para a documentação do componente na página principal.

2024-01-04 16:13 UTC, tiagopapile commented on resources/views/components/card/card-featured.blade.php
O caminho deve ser /components/cards/

2024-01-04 16:13 UTC, tiagopapile commented on app/View/Components/Card/CardFeatured.php
O caminho deve ser /components/cards/

2024-01-04 16:14 UTC, tiagopapile commented on app/View/Components/Card/CardFeatured.php
Alterar também o namespace.

2024-01-04 16:21 UTC, tiagopapile commented on tests/unit/components/CardFeaturedTest.php
Colocar na mesma estrutura de pastas do controller e da view.

2024-01-04 16:21 UTC, tiagopapile commented on tests/unit/components/CardFeaturedTest.php
Alterar também o namespace

2024-01-04 16:22 UTC, tiagopapile commented on docs/components/card-featured/README.md
Colocar na mesma estrutura de pasta do controller e da view.

2024-01-05 19:24 UTC, jeffersonrucustudiovisual commented on app/View/Components/Card/CardFeatured.php
> +        if (empty($post)) {
Ajuste realizado [3082dcf](https://github.com/studiovisual/base-theme/pull/42/commits/3082dcf31fb315170d5d04f85677a2a40baab7a8)

2024-01-05 19:25 UTC, jeffersonrucustudiovisual commented on app/View/Components/Card/CardFeatured.php
> +        $this->readingTime     = reading_time($this->post->ID);
Ajuste realizado [a0ec10e](https://github.com/studiovisual/base-theme/pull/42/commits/a0ec10e7b696a3a72e38dc7328bc81cc4d8e5f9f)

2024-01-05 19:54 UTC, jeffersonrucustudiovisual commented on resources/views/components/card/card-featured.blade.php
> +      @thumbnail($post, 'full')
Ajuste realizado [7be56c4](https://github.com/studiovisual/base-theme/pull/42/commits/7be56c4ed0b1b4dd3632acedc89202d1d4789db2)

2024-01-05 20:01 UTC, jeffersonrucustudiovisual commented on app/View/Components/Card/CardFeatured.php
Ajuste realizado

2024-01-05 20:01 UTC, jeffersonrucustudiovisual commented on tests/unit/components/CardFeaturedTest.php
Ajuste realizado

2024-01-05 20:01 UTC, jeffersonrucustudiovisual commented on docs/components/card-featured/README.md
Ajuste realizado

2024-01-05 20:01 UTC, jeffersonrucustudiovisual commented on resources/views/components/card/card-featured.blade.php
Ajuste realizado

2024-01-05 20:01 UTC, jeffersonrucustudiovisual commented on resources/views/components/card/card-featured.blade.php
> +      @thumbnail($post, 'full')
Ajuste realizado

2024-01-06 00:30 UTC, tiagopapile commented on app/View/Components/Cards/CardFeatured.php
> +        $this->categories  = get_the_category($this->post->ID);
O if deve estar antes dessa linha, sem isso as próximas linhas podem dar erro.

2024-01-06 00:31 UTC, tiagopapile commented on docs/components/card-featured/README.md
Ainda não está na estrutura de pastas adequada.

2024-01-06 20:21 UTC, tiagopapile commented on resources/views/components/cards/card-featured.blade.php
> +@if($post)
Utilizar `@notempty`

2024-01-06 20:21 UTC, tiagopapile commented on resources/views/components/cards/card-featured.blade.php
> +  <article
A tag article está duplicada.

2024-01-09 13:15 UTC, jeffersonrucustudiovisual commented on resources/views/components/cards/card-featured.blade.php
> +  <article
Ajuste realizado [f52e86b](https://github.com/studiovisual/base-theme/pull/42/commits/f52e86be0175c25dfd28b3e59049ba51c71da507)

2024-01-09 13:15 UTC, jeffersonrucustudiovisual commented on resources/views/components/cards/card-featured.blade.php
> +@if($post)
Ajuste realizado [f52e86b](https://github.com/studiovisual/base-theme/pull/42/commits/f52e86be0175c25dfd28b3e59049ba51c71da507)

2024-01-09 13:43 UTC, jeffersonrucustudiovisual commented on app/View/Components/Cards/CardFeatured.php
> +        $this->categories  = get_the_category($this->post->ID);
Ajuste realizado [201969d](https://github.com/studiovisual/base-theme/pull/42/commits/201969dbf31045deb88123ba0d9bd4bdafc3e7c9)

2024-01-09 13:44 UTC, jeffersonrucustudiovisual commented on docs/components/card-featured/README.md
Ajuste realizado tanto para docs/ quando para tests/

2024-01-11 05:27 UTC, jeffersonrucustudiovisual commented on resources/views/components/card/card-featured.blade.php
> +    <div class="card-featured__content flex flex-col gap-[10px] absolute bottom-0 left-0 w-full {{ $classes['content'] }}">
Ajuste realizado [629d363](https://github.com/studiovisual/base-theme/pull/42/commits/629d363f8de3ee3874ba6cbf1a3301f0dacc15d2)

2024-01-11 12:39 UTC, aresnoname commented on tests/unit/components/cards/CardFeaturedTest.php
> +                $wp_post = Mockery::mock('WP_Post');
Faltou alinhar as variáveis

2024-01-11 12:45 UTC, aresnoname commented on docs/components/cards/featured/README.md
> +### post &nbsp; `WP_Post || int`
Ajustar para `WP_Post|int` pois dessa forma fica no padrão das linguagens.
E você já mencionando que aceita Post ou ID do post na descrição do parâmetro.

2024-01-11 13:09 UTC, jeffersonrucustudiovisual commented on docs/components/cards/featured/README.md
> +### post &nbsp; `WP_Post || int`
Ajuste realizado [d72ae63](https://github.com/studiovisual/base-theme/pull/42/commits/d72ae637ba8b61d02355e8712233cc7879beb4f4)

2024-01-11 13:32 UTC, aresnoname approved these changes
Por mim está aprovado

2024-01-12 19:54 UTC, tiagopapile approved these changes
OK

2024-01-12 19:54 UTC, merged