tb-26 Adiciona componente ADS
studiovisual/base-theme pull request #43
Opened 2024-01-02 04:16 UTC by aresnoname

# Ads

Componente exibe publicidade.

## Utilização

   ```blade
   <x-ads> </x-ads>
   ```

## Parâmetros

### width &nbsp; `string`

- Define a largura do componente.

### height &nbsp; `string`

- Define a altura do componente.

## Exemplo

   ```blade
   <x-ads width="300" height="100">
      // Code Ads
   </x-ads>
   ```

<p align="right">(<a href="../../README.md">voltar</a>)</p>

2024-01-02 21:00 UTC, tiagopapile commented on app/View/Components/Common/Ads.php
> +    public string $classes = 'flex justify-center items-center border-[2px] border-solid border-info bg-info-light text-h5 text-info font-[500]'; //phpcs:ignore
Substituir` font-[500]` por `font-medium`.

2024-01-02 21:08 UTC, tiagopapile commented on app/View/Components/Common/Ads.php
> +    public string $width = '';
Parâmetro pode ser número.

2024-01-02 21:08 UTC, tiagopapile commented on app/View/Components/Common/Ads.php
> +    public string $height = '';
Parâmetro pode ser número.

2024-01-02 21:18 UTC, tiagopapile commented on app/View/Components/Common/Ads.php
> +    public function __construct(string $width = '300', string $height = '100', string $displayTitle = 'true') {
Width e height devem ser números.

Sugestão:

`string $title = 'Publicidade'`

Dessa forma pode-se definir um título customizado se necessário, se for passado uma string vazia não exibe o título.

2024-01-02 21:27 UTC, tiagopapile commented on docs/components/common/ads/README.md
> +Componente exibe publicidade.
Descrever um pouco mais o componente.

2024-01-02 21:39 UTC, tiagopapile commented on resources/views/components/common/ads.blade.php
> +        <div class="uppercase text-center text-neutral-900 text-[10px] tracking-[1.5px] mb-[2px]">
Recomendo utilizar span nesse caso.

2024-01-02 21:41 UTC, tiagopapile commented on resources/views/components/common/ads.blade.php
> +<section {{ $attributes->merge(['class' => '']) }}>
Se não há class, não há necessidade de fazer merge. Só utilizar:

{{ $attributes }}

2024-01-02 21:43 UTC, tiagopapile requested changes
Verificar comentários.

2024-01-05 11:48 UTC, aresnoname commented on app/View/Components/Common/Ads.php
> +    public string $classes = 'flex justify-center items-center border-[2px] border-solid border-info bg-info-light text-h5 text-info font-[500]'; //phpcs:ignore
Foi ajustado

2024-01-05 11:48 UTC, aresnoname commented on app/View/Components/Common/Ads.php
> +    public string $width = '';
Foi ajustado

2024-01-05 11:48 UTC, aresnoname commented on app/View/Components/Common/Ads.php
> +    public function __construct(string $width = '300', string $height = '100', string $displayTitle = 'true') {
Foi ajustado conforme o orientado

2024-01-05 11:49 UTC, aresnoname commented on docs/components/common/ads/README.md
> +Componente exibe publicidade.
Foi ajustando, verificar se está ok

2024-01-05 11:49 UTC, aresnoname commented on resources/views/components/common/ads.blade.php
> +        <div class="uppercase text-center text-neutral-900 text-[10px] tracking-[1.5px] mb-[2px]">
Foi ajustado

2024-01-05 11:50 UTC, aresnoname commented on resources/views/components/common/ads.blade.php
> +<section {{ $attributes->merge(['class' => '']) }}>
Foi ajustado

2024-01-08 18:46 UTC, tiagopapile approved these changes
OK.

2024-01-08 18:46 UTC, merged