tb-35 Ajustes de acessibilidade e organização
studiovisual/base-theme pull request #44
Opened 2024-01-02 05:04 UTC by aresnoname

2024-01-03 17:47 UTC, aresnoname reviewed
Explicando alguns pontos que foram modificados.

2024-01-03 17:47 UTC, aresnoname commented on app/View/Components/Common/Button.php
> +            'default' => 'bg-transparent outline-transparent text-primary hover:bg-primary-light hover:text-primary-hover focus:outline-primary-hover disabled:outline-neutral-500 disabled:!text-neutr
O time de designer adicionou novas cores verdes para os botões.
Eles definiram como `green-text` e `green-text-hover` mas avisaram que pode ser modificado.

Eu mantive, mas caso ache melhor alterar, só avisar.

2024-01-03 17:47 UTC, aresnoname commented on app/View/Components/Forms/BaseInput.php
> +        'sm' => 'p-8 pr-[34px] text-xs h-[34px]',
Font-size:
* SM --> 12px
* MD --> 14px
* LG --> 16px

2024-01-03 17:47 UTC, aresnoname commented on app/View/Components/Forms/Dropdown.php
> +    protected array $dropdownIconClasses = [
o dropdown estava com alguns problemas referente ao icone que estava como `background-image`
não era possível modificar a cor do icone, sendo que no layout tinha diferença em `focus:` e `dark:`

então eu fiz uma modificação, adicionei um @svg na view e posicionei corretamente utilizando position `relative` `absolute`

mais detalhes na view.

2024-01-03 17:47 UTC, aresnoname commented on docs/components/README.md
> +[Alert](./common/alert/README.md) - Exibe mensagens de alerta
Foi organizado as pastas das documentações de acordo com o padrão de `controler` e `view`

2024-01-03 17:47 UTC, aresnoname commented on resources/views/components.blade.php
> +  @php
Eu modifiquei essa parte.
Agora no topo da página componentes há um select com todos os componentes.

Eles são inseridos automaticamente de acordo com o nome dos arquivos no playground.

Para o sistema de href.scrollSmoth funcionar, no playground é necessário ter uma div com id = `component-` + `nome do compoente igual ao nome no arquivo`

Exemplo:
* `alert.blade.php` -> `component-alert`

2024-01-03 17:47 UTC, aresnoname commented on resources/views/components/common/logo.blade.php
> +<a href="{{ $url }}" rel="home" {{ $attributes->merge(['class' => 'logo font-headline text-lg text-neutral-900']) }}>
Quando o wordpress não tinha logo, aparecia o nome do wordpress com a cor `preta` isso causava problemas no `darkMode`.

2024-01-03 17:47 UTC, aresnoname commented on resources/views/components/forms/dropdown.blade.php
> +    <select {{ $attributes->merge(['class' => 'dropdown__select [&:has(option[value=""]:checked)]:text-neutral-500 ' . $classes]) }} aria-describedby="{{ ($attributes['id'] . '-description') ?? '' }}
Foi adicionado `aria-describedby` para identificar que a descrição abaixo pertence ao input.

Também foi adicionado um icone `svg` substituindo o icone como `background-image`

2024-01-03 17:47 UTC, aresnoname commented on resources/views/playground/components/alert.blade.php
> +  <strong class="block text-h5 my-16 text-neutral-900">Default</strong>
O `LightHouse` estava reportando erro por conta de utilizar `H2` depois `H5`, então removi e coloquei `strong` para melhorar a acessibilidade de acordo com a orientação do QA na descrição da tarefa

2024-01-03 17:47 UTC, aresnoname commented on resources/views/playground/components/checkbox.blade.php
> +        <label for="checkbox-default-nolabel" class="text-neutral-500 mb-12 italic">Normal</label>
O `LightHouse` estava reportando erro nos checkbox sem `label` então adicionei o texto acima do checkbox como `label`, isso irá resolver os erros na página de `componentes`

2024-01-03 17:47 UTC, aresnoname commented on resources/views/playground/components/dropdown.blade.php
> +        <x-dropdown id="dropdown-sm-default" size="sm" label="Seu título aqui" description="Esta é a área de descrição" :options="$options"></x-dropdown>
Foi adicionado `ID` para o `aria-describedby` funcionar corretamente

2024-01-03 17:47 UTC, aresnoname commented on tailwind.config.js
> +        text        : 'rgb(var(--color-green-text) / <alpha-value>)',
Novas cores `green` adicionadas

2024-01-04 11:09 UTC, aresnoname commented on resources/views/components/common/button.blade.php
> +  <span>{!! $slot !!}</span>
Foi necessário adicionar adicionar a tag `span` por causa do navegador Safira 15.6

O navegador não reconhece texto puro como um `elemento HTML` por tanto a classe `[&[loading]_*]:opacity-0` não é aplicado ao texto puro ecoado pelo `$slot` por tanto ele fica visível durante o loading ativo.

Ai fica o icone de loading girando por cima do texto.

2024-01-05 02:08 UTC, tiagopapile commented on resources/views/components/forms/dropdown.blade.php
> +    <select {{ $attributes->merge(['class' => 'dropdown__select [&:has(option[value=""]:checked)]:text-neutral-500 ' . $classes]) }} aria-describedby="{{ ($attributes['id'] . '-description') ?? '' }}
Vamos precisar analisar o impacto dessa alteração.

2024-01-05 02:09 UTC, tiagopapile commented on resources/views/components/common/button.blade.php
> +  <span>{!! $slot !!}</span>
Vamos precisar analisar o impacto dessa alteração.

2024-01-05 02:09 UTC, tiagopapile commented on app/View/Components/Forms/Dropdown.php
> +    protected array $dropdownIconClasses = [
Vamos precisar analisar o impacto dessa alteração.

2024-01-05 02:09 UTC, tiagopapile requested changes
Precisamos analisar melhor os impactos das alterações em alguns componentes.

2024-01-08 20:13 UTC, tiagopapile approved these changes
OK.

2024-01-08 20:13 UTC, merged