tb-28 Componente web-share e web-toggletip
studiovisual/base-theme pull request #46
Opened 2024-01-05 01:11 UTC by tiagopapile

# Compartilhamento

Componente que permite compartilhar a página atual ou qualquer link externo.  

## Utilização

   ```blade
   <x-web-share></x-web-share>
   ```

## Parâmetros

### type &nbsp; `string`

- **button (padrão) -** Exibe um botão simples para utilização do componente
- **bar -** Exibe o componente como uma barra vertical

### text &nbsp; `string`

- Texto a ser utilizado no compartilhamento

### url &nbsp; `string`

- Url a ser utilizada no compartilhamento. Caso nenhuma seja definida, a url atual será utilizada

## Atributos

- **prefers-native -** Define se o componente irá utilizar o compartilhamento nativo do sitema, caso haja suporte

## Exemplo

   ```blade
   <x-web-share text="Texto" url="https://url" prefers-native>Compartilhar</x-web-share>
   ```
   
# Toggletip

Componente similar ao tooltip, utilizado para exibir conteúdo adicional no clique.  

## Utilização

   ```blade
   <x-web-toggletip></x-web-toggletip>
   ```

## Parâmetros

### position &nbsp; `string`

- **bottom (padrão) -** Exibe o componente para baixo
- **top -** Exibe o componente para cima
- **left -** Exibe o componente à esquerda
- **right -** Exibe o componente à direita

## Exemplo

   ```blade
   <x-web-toggletip postion="top">Conteúdo de exemplo</x-web-toggletip>
   ```

2024-01-05 11:16 UTC, aresnoname requested changes
Revisar pontos

2024-01-05 11:16 UTC, aresnoname commented on app/View/Components/Navigation/WebShare.php
> +            'url' => 'mailto:?&subject=%text&body=%url'
Faltou alinhar o array

2024-01-05 11:16 UTC, aresnoname commented on resources/scripts/components/navigation/web-share.js
> +    // establish prototype chain
Dúvida: Acho que esse comentário pode ser removido, não ?
ficando igual na classe `WebToggletip`

2024-01-08 15:01 UTC, tiagopapile commented on resources/scripts/components/navigation/web-share.js
> +    // establish prototype chain
Não faz muita diferença, mas segui o padrão deixando o comentário e colocando onde estava faltando.

2024-01-08 15:01 UTC, tiagopapile commented on app/View/Components/Navigation/WebShare.php
> +            'url' => 'mailto:?&subject=%text&body=%url'
Corrigido.

2024-01-08 15:10 UTC, richarditokazo requested changes
Corrigir miss type xD

2024-01-08 15:10 UTC, richarditokazo commented on docs/components/navigation/web-share/README.md
> +- **prefers-native -** Define se o componente irá utilizar o compartilhamento nativo do sitema, caso haja suporte
sitema = sistema

2024-01-08 15:13 UTC, tiagopapile commented on docs/components/navigation/web-share/README.md
> +- **prefers-native -** Define se o componente irá utilizar o compartilhamento nativo do sitema, caso haja suporte
Corrigido.

2024-01-08 15:19 UTC, richarditokazo approved these changes
Está Ok.

2024-01-08 18:31 UTC, merged