tb-9 Adiciona header Mobile / Desktop
studiovisual/base-theme pull request #56
Opened 2024-01-19 06:10 UTC by aresnoname

2024-01-22 14:57 UTC, aresnoname reviewed
Alguns pontos

2024-01-22 14:57 UTC, aresnoname commented on app/Options/Footer.php
> +class Footer extends Field {
Ajusta a indexação das chaves, ficando no padrão.

2024-01-22 14:57 UTC, aresnoname commented on resources/views/components/common/logo.blade.php
> +<a href="{{ $url }}" rel="home" {{ $attributes->merge(['class' => 'logo flex items-center justify-center font-headline text-lg text-neutral-900']) }}>
Ajusta a logo para ela ficar sempre centralizada, mesmo sendo texto ou imagem.

2024-01-22 14:57 UTC, aresnoname commented on resources/views/sections/header.blade.php
> +  <div class="container py-24 transition-all duration-500 flex flex-wrap items-center content-start overflow-hidden h-96 lg:h-auto lg:flex-nowrap lg:overflow-visible lg:flex-row [&>form]:mt-48 [&>for
esse monte de classe na div do container é para fazer a transição na hora de abrir a barra de pesquisa na resolução desktop.

e alguns `&>form` é porque as classes que são passadas no `x-search` vão direto para o input mas o componente criar uma div `<form></form>` e o input dentro.

sendo necessário manipular manualmente com css.

2024-01-23 13:14 UTC, tiagopapile commented on app/Options/Header.php
> +    public function fields()
Chave ficou na linha de baixo.

2024-01-23 13:15 UTC, tiagopapile commented on app/Options/Header.php
> +                'label'         => ThemeServiceProvider::translate('Exibir redes sociais no cabeçalho ?'),
Espaço sobrando antes do `?`

2024-01-23 13:17 UTC, tiagopapile commented on app/View/Composers/Header.php
> +        return [
Array desalinhado.

2024-01-23 13:19 UTC, tiagopapile commented on resources/scripts/utils/helpers.js
> +export function checkIsMobile() {
Pode dar return direto em `window.matchMedia('(max-width: 767px)').matches`

2024-01-23 13:20 UTC, tiagopapile commented on resources/scripts/utils/helpers.js
> +export function checkIsTablet() {
Pode dar return direto em `window.matchMedia('(min-width: 767px) and (max-width: 1024px)').matches`

2024-01-23 18:09 UTC, tiagopapile commented on resources/views/sections/header.blade.php
> +    <x-search class="header__input-search"></x-search>
Nesse ponto o form está fazendo o header ter 104px de altura, quando deveria ser 96px.

2024-01-23 18:10 UTC, tiagopapile commented on resources/views/sections/header.blade.php
> +    <button class="header__hamburguer !w-[44px] !h-[44px] !p-12 flex flex-col gap-4 justify-center items-center rounded group-[.navbar]:bg-background-3 group-[.search]:bg-background-3 md:ml-24 md:gro
Esse botão está sendo exibido no desktop.

2024-01-23 18:20 UTC, tiagopapile commented on resources/scripts/views/header.js
> +const header             = document.querySelector('.header');
Nesse caso é melhor definir um ID para se obter o header.

2024-01-23 18:21 UTC, tiagopapile commented on resources/scripts/views/header.js
> +const headerBackupHeight = document.querySelector('.header').offsetHeight;
Utilizar a variável header ao invés de buscá-lo novamente.

2024-01-23 18:21 UTC, tiagopapile commented on resources/scripts/views/header.js
> +const headerDropdowns    = document.querySelectorAll('.header .dropdown');
Ao invés de utilizar document, pode usar a variável header para selecionar somente dentro dele.

2024-01-23 18:21 UTC, tiagopapile commented on resources/scripts/views/header.js
> +const headerHamburguer   = document.querySelector('.header .header__hamburguer');
Ao invés de utilizar document, pode usar a variável header para selecionar somente dentro dele.

2024-01-23 18:23 UTC, tiagopapile commented on resources/scripts/views/header.js
> +        const navbar          = document.querySelector('.header__navbar');
Guardar isso no começo do script.

2024-01-23 18:30 UTC, tiagopapile requested changes
Não sei se seria necessário tanto JS para o header. Algumas sugestões para avaliar se é possível de se fazer:

- O botão hamburguer ser um label que marca/desmarca um checkbox no header, dessa forma seria possível estilizar o header de acordo com o estado desse checkbox;
- A animação do menu mobile abrindo/fechando está um pouco travada, não daria para quando aberto ele ter a altura de 100vh e assim utilizar a transição do CSS?
- No desktop não daria para abrir os submenus apenas com o hover no link ao invés de utilizar JS?

2024-01-26 19:27 UTC, aresnoname commented on app/Options/Header.php
> +    public function fields()
Foi ajustado

2024-01-26 19:27 UTC, aresnoname commented on app/Options/Header.php
> +                'label'         => ThemeServiceProvider::translate('Exibir redes sociais no cabeçalho ?'),
Foi ajustado

2024-01-26 19:27 UTC, aresnoname commented on app/View/Composers/Header.php
> +        return [
Foi ajustado

2024-01-26 19:28 UTC, aresnoname commented on resources/scripts/utils/helpers.js
> +export function checkIsMobile() {
Foi ajustado

2024-01-26 19:28 UTC, aresnoname commented on resources/scripts/utils/helpers.js
> +export function checkIsTablet() {
Foi ajustado

2024-01-26 19:29 UTC, aresnoname commented on resources/views/sections/header.blade.php
> +    <x-search class="header__input-search"></x-search>
Foi ajustado

2024-01-26 19:30 UTC, aresnoname commented on resources/views/sections/header.blade.php
> +    <button class="header__hamburguer !w-[44px] !h-[44px] !p-12 flex flex-col gap-4 justify-center items-center rounded group-[.navbar]:bg-background-3 group-[.search]:bg-background-3 md:ml-24 md:gro
Ele estava sendo exibido porque ele era o X para fechar a barra de pesquisa quando aberta.
Na real que eu achei que seria interessante mas viajei nisso.

---
Foi ajustado, agora o próprio botão que abre a barra de pesquisa, também fecha.

2024-01-26 19:32 UTC, aresnoname commented on resources/scripts/views/header.js
> +const header             = document.querySelector('.header');
Esse código JS foi removido

2024-01-26 19:32 UTC, aresnoname commented on resources/scripts/views/header.js
> +const headerBackupHeight = document.querySelector('.header').offsetHeight;
Esse código JS foi removido

2024-01-26 19:32 UTC, aresnoname commented on resources/scripts/views/header.js
> +const headerDropdowns    = document.querySelectorAll('.header .dropdown');
Esse código JS foi removido

2024-01-26 19:33 UTC, aresnoname commented on resources/scripts/views/header.js
> +const headerHamburguer   = document.querySelector('.header .header__hamburguer');
Esse código JS foi removido

2024-01-26 19:33 UTC, aresnoname commented on resources/scripts/views/header.js
> +        const navbar          = document.querySelector('.header__navbar');
Esse código JS foi removido

2024-01-26 19:37 UTC, aresnoname commented
* Foi adicionado `checkbox` para manipular as ações de `Menu Mobile` e `Abrir a barra de pesquisa`
* Foi melhorada a animação de abrir o `Menu Mobile` mas talvez a animação da barra de pesquisa não tenha ficado tão bom.
* Desktop foi ajustado para não utilizar JS

2024-01-29 00:12 UTC, tiagopapile commented on resources/scripts/views/header.js
> +import { checkIsMobile, checkIsTablet } from "@scripts/utils/helpers";
Substituir aspas duplas por aspas simples em todo o JS.

2024-01-29 00:13 UTC, tiagopapile commented on resources/scripts/views/header.js
> +    const dropdowns = document.querySelectorAll(".dropdown");
Se esse JS pertence ao header, não faz sentido selecionar no documento inteiro. Primeiro obtenha o header e então selecione a partir dele.

2024-01-29 00:14 UTC, tiagopapile commented on resources/scripts/views/header.js
> +    dropdowns.forEach(dropdown => {
Use `dropdowns?.forEach` para não dar erro caso `dropdowns` não contenha elementos.

2024-01-29 00:16 UTC, tiagopapile commented on resources/scripts/views/header.js
> +        icon.addEventListener("click", () => {
Quando só há uma linha, pode omitir as chaves.

2024-01-29 00:24 UTC, tiagopapile requested changes
- No layout o botão de busca tem a mesma altura dos demais, isso não está acontecendo:
![image](https://github.com/studiovisual/base-theme/assets/82596706/79df01ea-567d-4a01-bf65-0f2072e84356)

- O espaçamento no mobile não está igual ao layout:
![image](https://github.com/studiovisual/base-theme/assets/82596706/77af1fdf-4b34-4b5f-8acd-63917ec52c25)

- No mobile o menu não está 100% de largura: 
![image](https://github.com/studiovisual/base-theme/assets/82596706/47a07292-c995-4fb0-a7d2-43c5d4b8cb19)

- Também no mobile o padding parece diferente
- Input de busca está sem placeholder

2024-01-29 18:10 UTC, aresnoname commented on resources/scripts/views/header.js
> +    const dropdowns = document.querySelectorAll(".dropdown");
Foi ajustado conforme o orientado

2024-01-29 18:10 UTC, aresnoname commented on resources/scripts/views/header.js
> +        icon.addEventListener("click", () => {
ok, foi ajustado

2024-01-30 16:59 UTC, tiagopapile commented on resources/scripts/views/header.js
> +const header  = document.getElementById('header');
- Colocar essa linha para dentro do `if`;
- Ajustar espaço sobrando antes do `=`

2024-01-30 17:01 UTC, tiagopapile requested changes
Verificar comentário.

2024-01-30 17:09 UTC, aresnoname commented on resources/scripts/views/header.js
> +const header  = document.getElementById('header');
Foi ajustado

2024-01-30 17:11 UTC, tiagopapile approved these changes
OK.

2024-01-30 18:13 UTC, merged