Adiciona seção Footer
studiovisual/base-theme pull request #7
Opened 2023-12-01 09:56 UTC by aresnoname

2023-12-01 15:46 UTC, richarditokazo requested changes
Verificar os pontos.

2023-12-01 15:46 UTC, richarditokazo commented on resources/views/sections/footer.blade.php
> +    <div class="order-3 md:order-first md:mr-auto">Copyright © 2023 Layout Base. Todos os direitos reservados.</div>
No Copyright adicionar date('Y') para ser dinâmico sempre o ano

2023-12-01 16:05 UTC, tiagopapile commented on app/Options/General.php
> +<?php
Remover configurções que não serão utilizadas ou que já possuem um valor padrão. Exemplo:

'instructions'      => '',
'required'          => 0,
'conditional_logic' => [],
'default_value'     => '',

2023-12-01 16:09 UTC, tiagopapile commented on app/View/Composers/Navigation.php
> +    $return = Navi::build($menu);
Não é recomendável criar uma variável chamada $return, pois isso acaba confundindo.

2023-12-01 16:13 UTC, tiagopapile commented on app/View/Composers/Navigation.php
> +    'sections.footer',
Já que é um controller de Navigation, não faria mais sentido a view ser específica para navigation também ao invés do Footer?

Outra possobilidade é mudar esse controller para Footer e então controlar o footer como um todo.

2023-12-01 16:15 UTC, tiagopapile commented on app/View/Composers/SocialMedia.php
> +        'sections.footer'
Mesmo caso do controller anterior. Vamos manter o controller associado a sua respectiva view, ou então centralizar no controller Footer.

2023-12-01 16:20 UTC, tiagopapile commented on app/View/Composers/SocialMedia.php
> +        $social_media_sections = get_field('show_social_media_sections', 'general');
Podemos otimizar isso. No Sage 10 é possível usar variáveis que já foram definidas em outros controllers, usando o conceito de herança.

Se essas opções são gerais do site, usar o get_field em vários controllers de forma separada irá aumentar a quantidade de querys ao banco.

Uma alternativa seria obter esses dados no controller App, e então utilizar nos demais controllers.

Mais detalhes nessa parte da documentação: https://roots.io/sage/docs/composers/

2023-12-01 16:21 UTC, tiagopapile commented on app/View/Composers/SocialMedia.php
> +        if ($this->view->name() == 'sections.footer' && $social_media_sections['social_media_footer'] == 1) {
Novamente, esse if da view não é necessário.

2023-12-01 16:21 UTC, tiagopapile commented on app/View/Composers/SocialMedia.php
> +        if ($this->view->name() == 'sections.footer' && $social_media_sections['social_media_footer'] == 1) {
Verificar algum campo utilizando empty é mais seguro.

2023-12-01 16:22 UTC, tiagopapile commented on app/View/Composers/SocialMedia.php
> +        $return = get_field('follow_social_media', 'general');
Verificar comentários anteriores sobre nome de variável e uso do get_field.

2023-12-01 16:23 UTC, tiagopapile commented on app/setup.php
>      register_nav_menus([
Array desalinhado.

2023-12-01 16:24 UTC, tiagopapile commented on app/setup.php
> +        'footer_primary_navigation' => __('Footer Primary Navigation', 'sage'),
text_domain não é o sage, vamos utilizar o definido no arquivo style.css.

2023-12-01 16:26 UTC, tiagopapile commented on resources/images/icons/facebook-f.svg
Não poderia ser apenas Facebook?

2023-12-01 16:31 UTC, tiagopapile commented on resources/views/sections/footer.blade.php
> +          <a class="block" href="{{ $footer_social_media["social_media_instagram"] }}">@svg("images.icons.instagram", "fill-current text-neutral-900", "Instagram")</a>
Para utilizar os ícones, recomendo esse padrão que não é necessário passar o caminho:

<x-icon-nome class="classes" />

2023-12-01 16:32 UTC, tiagopapile commented on resources/views/sections/footer.blade.php
> +          <a class="block" href="{{ $footer_social_media["social_media_instagram"] }}">@svg("images.icons.instagram", "fill-current text-neutral-900", "Instagram")</a>
@richarditokazo x-icon já é utilizado para se obter os ícones.

2023-12-01 16:36 UTC, tiagopapile commented on resources/views/sections/footer.blade.php
> +            "name" => $footer_primary_navigation["name"],
Sugestão: passar a variável $footer_primary_navigation como um todo ao invés de suas keys de forma individual.

2023-12-01 16:37 UTC, tiagopapile commented on resources/views/sections/footer.blade.php
> +        @include("partials.navigation.footer-navigation", [
Você pode encurtar o uso de `@notempty` e `@include` substituindo por `@includeWhen`.

2023-12-01 16:38 UTC, tiagopapile commented on resources/views/sections/footer.blade.php
> +    class="container text-[12px] text-neutral-500 mt-56 flex gap-16 flex-col items-center md:flex-row md:pt-24 md:mt-24 md:border-t border-solid border-neutral-300 ">
12px já está configurado no tailwind, utilizar a classe ao invés desse valor.

2023-12-01 16:38 UTC, tiagopapile commented on resources/views/sections/footer.blade.php
> +    class="container text-[12px] text-neutral-500 mt-56 flex gap-16 flex-col items-center md:flex-row md:pt-24 md:mt-24 md:border-t border-solid border-neutral-300 ">
Tem um espaço sobrando no final das classes.

2023-12-01 16:39 UTC, tiagopapile commented on resources/views/sections/footer.blade.php
> +    <a class="order-1 md:order-none" href="#term">Termos e Serviços</a>
Vamos manter o padão de pular linha entre os elementos no mesmo nível de hierarquia. Isso facilita a leitura do código.

2023-12-01 16:41 UTC, tiagopapile commented on resources/views/sections/footer.blade.php
> +    <div class="order-2 md:order-none bg-neutral-300 w-full h-[1px] my-24 md:w-[1px] md:h-[12px] md:my-0"></div>
Sugestão: Adicionar o valor 1px as configurações de spacing no tailwind.

2023-12-01 16:44 UTC, tiagopapile commented on resources/views/partials/navigation/footer-navigation.blade.php
> +    <div class="mb-4 text-base text-neutral-900">{{ $name }}</div>
Acho que faz mais sentido alguma tag de heading para esse título.

2023-12-01 16:45 UTC, tiagopapile requested changes
Verificar comentários.

2023-12-04 12:06 UTC, aresnoname commented on resources/views/sections/footer.blade.php
> +    <div class="order-3 md:order-first md:mr-auto">Copyright © 2023 Layout Base. Todos os direitos reservados.</div>
Foi ajustado, agora pega data e nome do projeto dinâmico.

2023-12-04 12:06 UTC, aresnoname commented on app/Options/General.php
> +<?php
Foi removido todas as opções que não eram utilizadas.

2023-12-04 12:08 UTC, aresnoname commented on app/View/Composers/Navigation.php
> +   * Returns the primary navigation.
Esse arquivo foi removido e a função realocada para helpers

2023-12-04 12:09 UTC, aresnoname commented on app/View/Composers/Navigation.php
> +    $return = Navi::build($menu);
Isso foi ajustado.

2023-12-04 12:10 UTC, aresnoname commented on app/View/Composers/Navigation.php
> +    'sections.footer',
Esse arquivo foi removido

2023-12-04 12:12 UTC, aresnoname commented on app/View/Composers/SocialMedia.php
> +        if ($this->view->name() == 'sections.footer' && $social_media_sections['social_media_footer'] == 1) {
O arquivo foi removido e foi adicionado um novo componente para social media

2023-12-04 12:13 UTC, aresnoname commented on app/View/Composers/SocialMedia.php
> +        if ($this->view->name() == 'sections.footer' && $social_media_sections['social_media_footer'] == 1) {
O arquivo foi removido e foi adicionado um novo componente para social media

2023-12-04 12:13 UTC, aresnoname commented on app/View/Composers/SocialMedia.php
> +        $return = get_field('follow_social_media', 'general');
O arquivo foi removido e foi adicionado um novo componente para social media

2023-12-04 12:16 UTC, aresnoname commented on resources/images/icons/linkedin-in.svg
Foi alterado

2023-12-04 12:17 UTC, aresnoname commented on resources/views/sections/footer.blade.php
> +          <a class="block" href="{{ $footer_social_media["social_media_instagram"] }}">@svg("images.icons.instagram", "fill-current text-neutral-900", "Instagram")</a>
eu não consegui utilizar <x-icon-dynamic> colocando valores dinâmicos para pegar ícones, pois foi falado que possivelmente no futuro teria opção o usuário selecionar as medias sociais.

então criei um novo componente especialmente para isso.

2023-12-04 12:18 UTC, aresnoname commented on resources/views/sections/footer.blade.php
> +            "name" => $footer_primary_navigation["name"],
Esse arquivo foi removido

2023-12-04 12:19 UTC, aresnoname commented on resources/views/sections/footer.blade.php
> +        @include("partials.navigation.footer-navigation", [
Foi ajustado conforme o orientado, além de ser chamado uma view partials

2023-12-04 12:21 UTC, aresnoname commented on resources/views/sections/footer.blade.php
> +    <div class="order-2 md:order-none bg-neutral-300 w-full h-[1px] my-24 md:w-[1px] md:h-[12px] md:my-0"></div>
terei isso em mente, obrigado.

2023-12-04 12:21 UTC, aresnoname commented on resources/views/sections/footer.blade.php
> +    <div class="order-2 md:order-none bg-neutral-300 w-full h-[1px] my-24 md:w-[1px] md:h-[12px] md:my-0"></div>
foi adicionado o spacing 1px w-1 h-1

2023-12-04 13:05 UTC, tiagopapile commented on app/Options/General.php
> +                    ->addGroup('follow_social_media', [
Sugestão: Nome ser apenas 'social_media'.

2023-12-04 13:07 UTC, tiagopapile commented on app/Options/General.php
> +                    ])
Como as redes sociais estão dentro de um grupo, o nome pode ser encurtado. Ex.: 'instagram'.

Vamos manter esse padrão para todos os casos em que isso se aplica.

2023-12-04 13:13 UTC, tiagopapile commented on app/Options/Footer.php
> +                'default_value' => 'Interdum risus ornare metus ultrices id. Faucibus adipiscing elementum libero fringilla. Fermentum vel bibendum ut nullam pulvinar.',
O default aqui pode ser vazio mesmo, assim caso não seja necessário utilizar a descrição no projeto, não vai ser preciso apagar esse texto.

2023-12-04 13:14 UTC, tiagopapile commented on app/Options/Footer.php
> +                'default_value' => 0,
Dúvida: Não seria ideal deixar como padrão exibir as redes sociais?

2023-12-04 13:16 UTC, tiagopapile commented on app/View/Composers/Footer.php
> +        $acf_general = $this->data->get('acfGeneral');
Pular linha antes de um if.

2023-12-04 13:26 UTC, tiagopapile commented on resources/views/partials/footer/navigation.blade.php
Remover linhas em branco antes e após o foreach. Também identar o foreach 1 nível.

2023-12-04 13:56 UTC, tiagopapile commented on app/View/Composers/App.php
> +            'acfGeneral' => get_field('general_group', 'general'),
Sugestão: trocar de `acfGeneral` para apenas `general` ou `settings`.

2023-12-04 13:58 UTC, tiagopapile commented on app/Options/General.php
> +            ->addGroup('general_group', [
Esse nome de campo não ficou muito bom. O ideal seria `general`.

2023-12-04 13:59 UTC, tiagopapile requested changes
Além dos comentários individuais, ajustar:

1. Definir uma constante para utilizarmos como prefixo de todos os campos
2. Definir uma constante para o text_domain do tema

2023-12-04 17:27 UTC, aresnoname commented on app/Options/General.php
> +                    ->addGroup('follow_social_media', [
Foi ajustado

2023-12-04 17:27 UTC, aresnoname commented on app/Options/General.php
> +                    ])
Foi ajustado

2023-12-04 17:27 UTC, aresnoname commented on app/Options/General.php
> +                        ->addPageLink('page_terms_services', [
Foi ajustado

2023-12-04 17:27 UTC, aresnoname commented on app/Options/General.php
> +                        ->addPageLink('page_privacy_policy', [
Foi ajustado

2023-12-04 17:27 UTC, aresnoname commented on app/Options/Footer.php
> +                'default_value' => 'Interdum risus ornare metus ultrices id. Faucibus adipiscing elementum libero fringilla. Fermentum vel bibendum ut nullam pulvinar.',
Foi ajustado

2023-12-04 17:41 UTC, aresnoname commented on app/Options/Footer.php
> +                'default_value' => 0,
Particularmente para mim não muda muito rsrs, é uma ação de 2x cliques.
Mas foi ajustado. agora o padrão é mostrar, mas caso o usuário não tenha configurado a URL, não irá mostrar aquela rede social.

2023-12-04 17:41 UTC, aresnoname commented on app/View/Composers/Footer.php
> +        $acf_general = $this->data->get('acfGeneral');
Foi ajustado

2023-12-04 17:42 UTC, aresnoname commented on app/View/Composers/Footer.php
> +        return [
Foi ajustado

2023-12-04 17:42 UTC, aresnoname commented on app/View/Composers/Footer.php
> +                'instagram' => $media['social_media_instagram'],
Foi ajustado

2023-12-04 17:42 UTC, aresnoname commented on resources/views/components/social-media.blade.php
> +            <a class="block" href="{{$url}}">@svg('images.icons.'.$name, $iconsStyle, $name)</a>
Foi ajustado

2023-12-04 17:43 UTC, aresnoname commented on resources/views/partials/footer/navigation.blade.php
> +    <nav class="flex flex-col gap-12 max-w-[192px] overflow-clip" aria-label="{{ $navigation['name'] }}">
o estranho que minha extensão tailwindcss vscode não está mostrando quando é usado max-w-192 apenas quando uso w-192, mas aparamente está funcionando normal

Foi ajustado.

2023-12-04 17:45 UTC, aresnoname commented on resources/views/partials/footer/navigation.blade.php
Foi ajustado.

2023-12-04 17:45 UTC, aresnoname commented on resources/views/sections/footer.blade.php
> +    <a class="order-1 md:order-none" href="{{$footer_copyright_pages['terms_services']}}">{{__('Terms and Services', 'base-theme')}}</a>
Foi ajustado

2023-12-04 17:46 UTC, aresnoname commented on resources/views/sections/footer.blade.php
> +  <div class="container text-sm text-neutral-500 mt-40 flex flex-col items-center md:flex-row md:gap-16 md:pt-24 md:mt-24 md:border-t border-solid border-neutral-300">
Foi ajustado

2023-12-04 17:46 UTC, aresnoname commented on resources/views/sections/footer.blade.php
> +    <div class="order-3 md:order-first md:mr-auto">Copyright © {{date('Y')}} {{$siteName}}. {{__('All rights reserved', 'base-theme')}}.</div>
Foi ajustado

2023-12-04 17:56 UTC, aresnoname commented on app/View/Composers/App.php
> +            'acfGeneral' => get_field('general_group', 'general'),
Foi ajustado

2023-12-04 17:56 UTC, aresnoname commented on app/Options/General.php
> +            ->addGroup('general_group', [
Foi ajustado

2023-12-07 16:37 UTC, tiagopapile commented on app/View/Composers/App.php
> +            'general'  => get_fields(BASETHEME_PREFIX . 'general'),
Sugestão: Criar o seguinte helper para deixar o código mais limpo

```
function prefix($value) {
return BASETHEME_PREFIX . $value;
}
```

2023-12-07 16:39 UTC, tiagopapile commented on app/View/Composers/Footer.php
> +            'footer_social_media' => $this->get_social_media($acf_fields['display_social_media'], $acf_general['social_media']),
Aqui ainda está 'footer_social_media'. Pode ser apenas 'social_media'.

2023-12-07 16:40 UTC, tiagopapile commented on app/View/Composers/Footer.php
> +            'footer_navigation'   => [
Aqui ainda está 'footer_navigation'. Pode ser apenas 'navigation'.

2023-12-07 16:40 UTC, tiagopapile commented on app/View/Composers/Footer.php
> +            'footer_copyright_pages' => $this->get_copyright_pages($acf_general['pages_settings']),
Aqui ainda está 'footer_copyright_pages'. Pode ser apenas 'copyright_pages'.

2023-12-07 16:42 UTC, tiagopapile commented on app/View/Composers/Footer.php
> +    public function get_social_media($display, $media) {
Nome do método deve seguir o padrão camelCase.

2023-12-07 16:42 UTC, tiagopapile commented on app/View/Composers/Footer.php
> +    public function get_copyright_pages($pages) {
Nome do método deve seguir o padrão camelCase.

2023-12-07 16:43 UTC, tiagopapile commented on app/View/Composers/Footer.php
> +            return [
Está retornando o array no mesmo formato de entrada, qual o intuito desse método?

2023-12-07 16:43 UTC, tiagopapile commented on app/View/Composers/Footer.php
> +        return [
Está retornando o array no mesmo formato de entrada, qual o intuito desse método?

2023-12-07 16:47 UTC, tiagopapile commented on resources/views/components/social-media.blade.php
> +                <a class="block" aria-label="{{ esc_attr($name) }}" href="{{ esc_url($url) }}" target="_blank">@svg('images.icons.' . esc_html($name), esc_attr($iconsStyle), esc_html($name))</a>
Acho que não é necessário utilizar as funções esc_attr, esc_url e esc_html pois o blade já trata isso.

2023-12-07 16:47 UTC, tiagopapile commented on resources/views/partials/footer/navigation.blade.php
Acho que não é necessário utilizar as funções esc_attr, esc_url e esc_html pois o blade já trata isso.

2023-12-07 16:51 UTC, tiagopapile commented on resources/views/sections/footer.blade.php
> +    @notempty($footer_copyright_pages['terms_services'] && $footer_copyright_pages['privacy_policy'])
Verificar dessa forma torna as duas páginas obrigatórias. O ideal seria verificar cada página individualmente.

2023-12-07 16:53 UTC, tiagopapile commented on app/Options/General.php
> +        $this->name   = __('Geral', BASETHEME_TEXT_DOMAIN);
Sugestão: Criar algum helper para deixar o código mais limpo, substituindo em todos os lugares necessários

function translate($value) {
return __($value, BASETHEME_TEXT_DOMAIN);
}

2023-12-08 22:26 UTC, aresnoname commented on resources/views/components/navigation/social-media.blade.php
> +                    @svg('images.icons.' . esc_html($name), 'fill-current text-neutral-900 hover:text-green transition-color duration-300', esc_html($name))
Aqui eu mantive as funções de escape do wordpress `esc_html($name)` pois recebe dados de um variável que será imprimido html na view por conta de `@svg`

2023-12-08 22:29 UTC, aresnoname commented on resources/views/sections/footer.blade.php
> +      @if (!\App\array_empty($social_media))
Se for aprovado o uso de função para verificar se as chaves do array não estão vazia, penso em tentar criar uma diretiva do blade para usar algo parecido com `@array_empty()` ou `@array_notempty()`

2023-12-08 22:37 UTC, aresnoname commented on app/View/Components/SocialMedia.php
> +        $this->type       = $this->types[$type] ?? $this->types['default'];
Foi ajustado

2023-12-08 22:37 UTC, aresnoname commented on app/View/Components/SocialMedia.php
> +    public function __construct($type = 'default', $iconsData = null, $iconsStyle = 'fill-current text-neutral-900 hover:text-green transition-color duration-300')
Foi ajustado

2023-12-08 22:37 UTC, aresnoname commented on app/View/Composers/App.php
> +            'general'  => get_fields(BASETHEME_PREFIX . 'general'),
Foi ajustado conforme na nossa call

2023-12-08 22:38 UTC, aresnoname commented on app/View/Composers/Footer.php
> +            'footer_social_media' => $this->get_social_media($acf_fields['display_social_media'], $acf_general['social_media']),
foi ajustado

2023-12-08 22:38 UTC, aresnoname commented on app/View/Composers/Footer.php
> +            'footer_description'  => $acf_fields['description'],
foi ajustado

2023-12-08 22:38 UTC, aresnoname commented on app/View/Composers/Footer.php
> +            'footer_copyright_pages' => $this->get_copyright_pages($acf_general['pages_settings']),
foi ajustado

2023-12-08 22:38 UTC, aresnoname commented on app/View/Composers/Footer.php
> +    public function get_social_media($display, $media) {
essa função foi removida

2023-12-08 22:38 UTC, aresnoname commented on app/View/Composers/Footer.php
> +    public function get_copyright_pages($pages) {
essa função foi removida

2023-12-08 22:42 UTC, aresnoname commented on app/View/Composers/Footer.php
> +            return [
Era porque antes os o nome das chaves era por exemplo `$acf['footer_social_media_instragram']` e eu precisava apenas de ['Instagram' => 'link do instagram'] para pegar o nome da chave `instagram` e usar para pegar o icone, por exemplo `@svg(images.icons'.$instagram)`

---

Mas depois de algumas mudanças tudo foi modificado e eu não vi que não fazia mais sentido usar.

Essa função foi removida.

2023-12-08 22:43 UTC, aresnoname commented on app/View/Composers/Footer.php
> +        return [
Essa função foi removida

2023-12-08 22:43 UTC, aresnoname commented on resources/views/components/social-media.blade.php
> +                <a class="block" aria-label="{{ esc_attr($name) }}" href="{{ esc_url($url) }}" target="_blank">@svg('images.icons.' . esc_html($name), esc_attr($iconsStyle), esc_html($name))</a>
essas função de escape foram removida.

2023-12-08 22:44 UTC, aresnoname commented on resources/views/partials/footer/navigation.blade.php
essas funções de escape foram removidas

2023-12-08 22:44 UTC, aresnoname commented on resources/views/components/social-media.blade.php
Foi ajustado para o local orientado

2023-12-08 22:45 UTC, aresnoname commented on resources/views/sections/footer.blade.php
> +    @notempty($footer_copyright_pages['terms_services'] && $footer_copyright_pages['privacy_policy'])
Agora foi feito uma verificação para ver se há algumas delas disponível para exibir, pois foi necessário para não exibir a div decorativa caso nenhuma página vá ser exibida.

E também foi feito a verificação individual de cada uma.

2023-12-08 22:46 UTC, aresnoname commented on app/Options/General.php
> +        $this->name   = __('Geral', BASETHEME_TEXT_DOMAIN);
Foi ajustado conforme nossa call

2023-12-11 01:24 UTC, tiagopapile commented on app/Options/Footer.php
> +        $this->post   = BASETHEME_PREFIX . 'footer';
Faltou utilizar o helper.

2023-12-11 02:03 UTC, tiagopapile commented on docs/components/social-media/README.md
> +## Exemplo
Título deve ser no plural.

2023-12-11 02:06 UTC, tiagopapile commented on docs/components/social-media/README.md
> +   ```blade
Como o que mudou foram apenas os valores dos parâmetros, um exemplo já é o suficiente.
Não é necessário exemplo pra dizer que se pode usar class.

2023-12-11 02:13 UTC, tiagopapile commented on resources/views/components/navigation/social-media.blade.php
> +    @notempty($iconsData && is_array($iconsData))
Essa verificação deveria ficar na linha de cima, assim não ficaria uma div vazia caso não tenha itens.

2023-12-11 02:24 UTC, tiagopapile commented on resources/views/components/navigation/social-media.blade.php
> +    @notempty($iconsData && is_array($iconsData))
Essa variável pode retornar um array vazio no controller caso seja null, assim não será necessário verificar se é um array.

2023-12-11 02:55 UTC, tiagopapile commented on tests/unit/components/SocialMediaTest.php
> +      $expected_icon_data = [
Porque a key 'icon'?

2023-12-11 03:03 UTC, tiagopapile commented on tests/unit/components/SocialMediaTest.php
> +    public function testRendersCorrectSocialMediaTestPersonalizedComplet(): void {
Não entendi essa variação Test Personalized.

2023-12-11 03:16 UTC, tiagopapile commented on resources/views/sections/footer.blade.php
> +    @if (isset($copyright_pages) &&!\App\array_empty($copyright_pages))
Essa variável sempre será definida, não sendo necessário utlizar isset().

2023-12-11 03:16 UTC, tiagopapile commented on resources/views/sections/footer.blade.php
> +      @if (isset($navigation) && !empty($navigation))
Essa variável sempre será definida, não sendo necessário utlizar isset().

2023-12-11 03:17 UTC, tiagopapile commented on app/View/Components/SocialMedia.php
> +        'default'  => 'flex gap-24',
O nome do tipo deve ser `horizontal` e ele pode ser tratado como a opção default.

2023-12-11 03:17 UTC, tiagopapile commented on app/View/Components/SocialMedia.php
> +    public $types = [
As classes que se repetem pode ficar na variável $classes.

2023-12-11 03:22 UTC, tiagopapile requested changes
Verificar comentários.

2023-12-11 14:45 UTC, aresnoname commented on tests/unit/components/SocialMediaTest.php
> +      $expected_icon_data = [
por que é utilizado para passar os dados dos ícones. acho que fica mais claro de entender no futuro, não ?

2023-12-11 14:46 UTC, aresnoname commented on tests/unit/components/SocialMediaTest.php
> +    public function testRendersCorrectSocialMediaTestPersonalizedComplet(): void {
Essa variação é para testar erros que outras pessoas podem cometer ao utilizar o componente.

Eu coloco valores aleatórios e verifico se vai retornar o padrão, sem que o componente quebre.

2023-12-11 16:51 UTC, aresnoname commented on app/Options/Footer.php
> +        $this->post   = BASETHEME_PREFIX . 'footer';
Foi ajustado

2023-12-11 16:54 UTC, aresnoname commented on app/helpers.php
> +function array_empty($array) {
Duvida: 
* Por que usar a função `array_filter` seria melhor ?
* Tem necessidade de verificar o array recursivamente ?  não seria verificações demais dependendo do caso ?

2023-12-11 16:54 UTC, aresnoname commented on resources/views/components/navigation/social-media.blade.php
> +    @notempty($iconsData && is_array($iconsData))
foi ajustado

2023-12-11 16:54 UTC, aresnoname commented on resources/views/components/navigation/social-media.blade.php
> +    @notempty($iconsData && is_array($iconsData))
foi ajustado conforme o orientado

2023-12-11 16:55 UTC, aresnoname commented on app/View/Components/SocialMedia.php
> +        'default'  => 'flex gap-24',
Foi ajustado

2023-12-11 16:55 UTC, aresnoname commented on app/View/Components/SocialMedia.php
> +    public $types = [
Foi ajustado mas a chave `horizontal` ficou vazia.

2023-12-11 20:59 UTC, aresnoname commented on app/helpers.php
> +function array_empty($array) {
Foi ajustado conforme orientado em call

2023-12-11 21:00 UTC, aresnoname commented on resources/views/sections/footer.blade.php
> +    @if (isset($copyright_pages) &&!\App\array_empty($copyright_pages))
foi ajustado conforme orientado em call

2023-12-11 21:00 UTC, aresnoname commented on resources/views/sections/footer.blade.php
> +      @if (isset($navigation) && !empty($navigation))
foi ajustado conforme orientado em call

2023-12-11 21:06 UTC, aresnoname commented on tests/unit/components/SocialMediaTest.php
> +      $expected_icon_data = [
Foi explicado em call e ajustado conforme o orientado

2023-12-11 21:07 UTC, aresnoname commented on tests/unit/components/SocialMediaTest.php
> +    public function testRendersCorrectSocialMediaTestPersonalizedComplet(): void {
Foi explicado em call e ajustado conforme o orientado

2023-12-11 22:10 UTC, aresnoname commented on tests/unit/components/SocialMediaTest.php
> +     * @testdox Testa tipagem errada de parâmetro 'type' esperando retornar positivo
Adicionado testes para testar tipagem do componente, está programado para forçar um erro e retornar `positivo`, caso algum erro não acontece o teste irá retornar `negativo`

2023-12-11 22:14 UTC, aresnoname commented on resources/views/components/navigation/social-media.blade.php
> +                @svg('images.icons.' . esc_html($name), 'fill-current text-neutral-900 hover:text-green transition-color duration-300', esc_html($name))
ficou faltando adicionar a classe utility com `[&_path]:fill-current` para remover a cor de qualquer svg que for utilizado.

2023-12-12 23:16 UTC, aresnoname commented on app/View/Components/SocialMedia.php
> +namespace App\View\Components;
Foi merge com as informações da `develop`, foi adicionado o componente `SocialMedia` em `Components\Navigation\SocialMedia`

2023-12-12 23:20 UTC, aresnoname commented on resources/views/components/navigation/social-media.blade.php
> +                @svg('images.icons.' . esc_html($name), 'fill-current text-neutral-900 hover:text-green transition-color duration-300', esc_html($name))
Após merge com as informações da `develop`, foi removido as funções `esc_html()` e adicionado a class `path-current`

2023-12-13 12:21 UTC, tiagopapile commented on app/View/Components/Navigation/SocialMedia.php
> +    public array $types = [
Faltou alinhar os itens do array.

2023-12-13 12:22 UTC, tiagopapile commented on app/View/Components/Navigation/SocialMedia.php
> +    public function __construct(string $type = 'horizontal', array $iconsData = [])
A chave deve ser na mesma linha do método.

2023-12-13 12:23 UTC, tiagopapile commented on app/View/Components/Navigation/SocialMedia.php
> +    public function render()
A chave deve ser na mesma linha do método.

2023-12-13 12:25 UTC, tiagopapile commented on docs/components/README.md
> -[Dark mode](./dark-mode/README.md) - Controla o modo claro/escuro no site
Esses espaços estão sendo removidos automaticamente? Pois são eles que fazem a quebra de linha no arquivo.

2023-12-13 12:27 UTC, tiagopapile requested changes
Verificar comentários.

2023-12-13 12:36 UTC, tiagopapile commented on resources/views/sections/footer.blade.php
> +
Linha sobrando.

2023-12-13 12:38 UTC, tiagopapile commented on resources/views/sections/footer.blade.php
> +    @includeWhen(!empty($navigation), 'partials.footer.navigation', $navigation)
Testando aqui no meu ambiente deu erro dizendo que a variável `$navigation` não existe, será necessário trocar para:

`@includeWhen(!empty($navigation), 'partials.footer.navigation', $navigation ?? [])`

2023-12-13 12:47 UTC, tiagopapile commented on resources/views/sections/footer.blade.php
> +    <div class="order-3 md:order-first md:mr-auto">Copyright © {{ date('Y') }} {{ $siteName }}. {{ \App\Providers\ThemeServiceProvider::translate('Todos os direitos reservados') }}.</div>
Texto não está centralizado no mobile.

2023-12-13 12:49 UTC, tiagopapile commented on app/Options/General.php
> +                'label' => ThemeServiceProvider::translate('Social media'),
Colocar título em português.

2023-12-13 12:49 UTC, tiagopapile commented on app/Options/General.php
> +                        'label'          => ThemeServiceProvider::translate('privacy_policy'),
Colocar título em português.

2023-12-13 13:13 UTC, aresnoname commented on app/Options/General.php
> +                'label' => ThemeServiceProvider::translate('Social media'),
Foi ajustado para `Redes sociais`

2023-12-13 13:14 UTC, aresnoname commented on app/Options/General.php
> +                        'label'          => ThemeServiceProvider::translate('privacy_policy'),
Foi ajustado para `Politica de Privacidade`

2023-12-13 13:14 UTC, aresnoname commented on app/View/Components/Navigation/SocialMedia.php
> +    public array $types = [
Foi ajustado

2023-12-13 13:14 UTC, aresnoname commented on app/View/Components/Navigation/SocialMedia.php
> +    public function __construct(string $type = 'horizontal', array $iconsData = [])
Foi ajustado

2023-12-13 13:14 UTC, aresnoname commented on app/View/Components/Navigation/SocialMedia.php
> +    public function render()
Foi ajustado

2023-12-13 13:16 UTC, aresnoname commented on docs/components/README.md
> -[Dark mode](./dark-mode/README.md) - Controla o modo claro/escuro no site
Isso acontece ao trazer as informações da develop e resolver os conflitos.
Acabou que ficou tudo junto e não percebi que era a quebra de linha.

Foi ajustado e me atentarei a isso nos próximos PR

2023-12-13 13:16 UTC, aresnoname commented on resources/views/sections/footer.blade.php
> +
Foi ajustado

2023-12-13 13:16 UTC, aresnoname commented on resources/views/sections/footer.blade.php
> +    @includeWhen(!empty($navigation), 'partials.footer.navigation', $navigation)
Foi ajustado conforme o orientado

2023-12-13 13:21 UTC, aresnoname commented on resources/views/sections/footer.blade.php
> +    <div class="order-3 md:order-first md:mr-auto">Copyright © {{ date('Y') }} {{ $siteName }}. {{ \App\Providers\ThemeServiceProvider::translate('Todos os direitos reservados') }}.</div>
Foi ajustado

2023-12-13 13:43 UTC, tiagopapile approved these changes
Aprovado :)

2023-12-13 13:56 UTC, richarditokazo approved these changes
Está OK.

2023-12-13 14:36 UTC, merged